### ISSUE TITLE
Missing service metadata.labels mapping

### ISSUE THREAD

**Issue by Journerist** [kubernetes/kompose#1010]
Hi,

first, I really like the project, thank you very much!

I am not able to map compose values to service's metadata.labels.

example:
```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.12.0-americium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 500M
    labels:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      kompose.service.type: LoadBalancer
```

The result is:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.4.0 (c7964e7)
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: selenium-hub
  type: LoadBalancer
status:
  loadBalancer: {}
```

What I need is the following:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.4.0 (c7964e7)
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
    dns: route53   <--- this field is missing
  name: selenium-hub
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: selenium-hub
  type: LoadBalancer
status:
  loadBalancer: {}
```
Maybe I missed something but I couldn't find any hint in the conversion matrix. I need to find a way to make Kompose creating the **dns: route53** label.

Any ideas how to achieve this?
