### ISSUE TITLE
Failing with my Node.js, RabbitMQ app

### ISSUE THREAD

**Issue by booboothefool** [kubernetes/kompose#1019]
The `node` and `rabbitmq` are failing to create working .yaml. For the `node`, it gives me `PersistentVolumeClaim`, but appears to be missing `PersistantVolume`? For the rabbitmq, it gives me a failing pod.

I was expecting to just be able to run `kompose convert` and then just dump the .yaml into the cloud. Please let me know if I am missing steps.

```
version: "3"

services:
  node:
    build: .
    volumes:
      - ~/.somedir:/root/.somedir
    ports:
      - 8085:8085
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    restart: on-failure
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  mongo1:
    image: mongo
    ports:
      - 27017:27017
    command: mongod --replSet rs0
  mongo2:
    image: mongo
    ports:
      - 27018:27017
    command: mongod --replSet rs0
  mongo3:
    image: mongo
    ports:
      - 27019:27017
    command: mongod --replSet rs0

networks:
  default:
      external:
          name: mynet
```

**Comment by hangyan** [comment]
@booboothefool PV is a environment specific resource, we cannot generate it from the compose file

**Comment by DanielRHayes** [comment]
@booboothefool Is your issue that the `persistent-volume-claim` isn't being generated? I think kompose will only generate a `persistent-volume-claim` if you explicitly set a volume in `docker-compose`.  This generates one for me.

```
version: "3"
services:
  mongo_1:
    image: mongo:latest
    volumes:
      - db-data:/data/db
volumes:
  db-data:
```

```
// db-data-persistentvolumeclaim.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
```
