### ISSUE TITLE
Support for converting docker-compose.yml files using YAML Merge Key

### ISSUE THREAD

**Issue by eengelking** [kubernetes/kompose#1038]
My team often uses YAML merge keys to keep our docker-compose.yml files small and to prevent repetition of tasks within the file.  Support for converting these would be very beneficial.  

http://yaml.org/type/merge.html

I'm currently receiving the following errors when attempting to convert the files ATM:

```Service 'portal' configuration key 'logging' contains an invalid type, it should be an array or object```

Example configuration:

```  
 cli:
    image: <imageURL>
    logging: &cli-logging
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: 5

  portal:
    image: <imageURL>
    logging:
      <<: *cli-labels
```
