### ISSUE TITLE
Multiple compose files seems to be broken

### ISSUE THREAD

**Issue by Uelb** [kubernetes/kompose#1048]
Hi,

I'm trying to convert 2 different compose files :

```yaml
# docker-compose.yml
version: '2'
services:
  app:
    command: script/run.sh
    ports:
      - 3000
  nginx:
    image: nginx
    volumes_from:
      - app
    depends_on:
      - app
```

And 
```yaml
# docker-compose.production.yml
version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: my_image
    volumes:
      - ./file_storage:/app/public/system/
      - assets:/app/public/assets/
    environment:
      PASS: ${PASS}
  nginx:
    ports:
      - 80
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
volumes:
  assets:
networks:
  nginx_default:
    external: true
```

I have an error when running : 
```
kompose convert --stdout -f docker-compose.yml -f docker-compose.production.yml

ERRO Could not parse config for project members : Service 'app' has neither an image nor a build context specified. At least one must be provided.
FATA composeObject.Parse() failed, Failed to load compose file: Service 'app' has neither an image nor a build context specified. At least one must be provided.
```

It seems like the docker-compose version takes priority and that the docker-compose production yml is not read. When I change the order of the -f options, I have a similar error with the nginx service having no build context.

My kompose version is 1.15.0 (e3cd4d4).
My OS is MAC OS High Sierra (10.13.14)

When using docker-compose cli, I successfully can run this configuration with `docker-compose -f docker-compose.yml -f docker-compose.production.yml up`

I have trouble understanding why it does not work correctly.
