### ISSUE TITLE
hostPort in deployment spec: is this supported?

### ISSUE THREAD

**Issue by prachidamle** [kubernetes/kompose#1054]
If I have a port mapping specified in docker-compose.yml file, using the recent Kompose tool release , the generated deployment.yaml does not have the hostPort specified.

Thus if my docker-compose.yml file says:
```
version: "2"
services:  
  result:
        image: tmadams333/example-voting-app-result:latest
        ports:
          - "5001:80"
```
Then how can I  specify that the public port "5001" be exposed as a hostPort in my k8s cluster?

If I deploy the generated *service.yaml and *deployment.yaml then my deployment does not get exposed on port 5001 as-is.
