### ISSUE TITLE
Convert version 3.5 of Docker Compose is not supported

### ISSUE THREAD

**Issue by jvitor83** [kubernetes/kompose#1058]
I have the following `docker-compose.yml`:
```
version: "3.5"

services:

  helloworld:
    image: tutum/hello-world
    ports:
      - 80:80
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network
```
Executing `docker-compose up` i can up my service using the [network `name` feature introduced at version 3.5](https://docs.docker.com/compose/compose-file/compose-versioning/#version-35)

> With that feature, i can use **multiples `docker-compose.yml`** and allow them to **connect to each other** using a **specific network name**

My idea is to use `kompose convert -f docker-compose.yml` and allow to generate the k8s ignoring the networks as it already does (not supported - and it is what i expect). 
But instead, it is given the following error: `Version 3.5 of Docker Compose is not supported. Please use version 1, 2 or 3`

**I guess it is time to update to allow a greater version of compose spec.**

_FYI: Even changing the version at docker-compose.yml to 3, the error kompose convert gives is: `Additional property name is not allowed`. But allowing use as version 3 is not a solution since `docker-compose up` doesn't work unless is 3.5._
