### ISSUE TITLE
Convert mounted directories into configmaps

### ISSUE THREAD

**Issue by mterron** [kubernetes/kompose#1060]
When a docker-compose file has a volume pointing to a local directory, Kompose should convert the content of the directory into a configmap and attach the configmap into the pod at the right path as per the volume definition.

Example docker-compose.yml
```yaml
version: "2.4"
services:
  web:
    image: nginx
    volumes:
      - ./tls:/etc/tls
    env_file: _env
```
Content of *./tls*:
```sh
$ ls tls/
ca.pem  web.pem  web.key
```

Configmap to be created should have 3 keys, ca.pem, web.pem and web.key with values as the content of those files. The configmap should be mounted at /etc/tls as per the docker-compose file spec.

**Comment by hangyan** [comment]
@cdrage This is a good solution. What's your opnion?

**Comment by leberknecht** [comment]
That would be great! E.g. i use to mount config files for nginx like 
```
 nc_nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
 ```
At the moment, `kompose` "only" detects that there is a mount and creates a `PersistentVolumeClaim`
