### ISSUE TITLE
kompose up - unmarshal errors when using docker compose version '3'

### ISSUE THREAD

**Issue by lakshmanvvs** [kubernetes/kompose#1064]
Using docker compose version 3, `kompose convert` creates deployment/service files, when using `kompose up`, I get
 `ERRO Could not parse config for project kubecompose : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `extensi...` into config.RawService
  line 2: cannot unmarshal !!str `Deployment` into config.RawService`

`kompose version
1.16.0 (0c01309)`  

Using Docker for Mac - OS - High Sierra 

``` docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.10.3
  StackAPI:         v1beta2
```

Expected behavior: `kompose up` deploys on kubernetes

**Comment by hangyan** [comment]
@lakshmanvvs Would you mind to paste a sample compose file that can reproduce these errors?

**Comment by lakshmanvvs** [comment]
@hangyan 
Sure 
```
version: "3"

services:
  inspections-aggregate-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: inspections-aggregate-service
    entrypoint: ./entrypoint.sh
    ports:
      - "7110:8080"
    environment:
      - https_proxy=${https_proxy}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - http_proxy=${http_proxy}
      - HTTP_PROXY=${HTTP_PROXY}
      - COUCHBASE_HOSTNAME=couchbase-server
      - COUCHBASE_BUCKET_NAME=vin-info
      - COUCHBASE_BUCKET_EDCRAY=bananarama
      - COUCHBASE_CLUSTER_USERNAME=Administrator
      - COUCHBASE_CLUSTER_EDCRAY=bananarama
      - COUCHBASE_KEY_VALUE_TIMEOUT=35000
      - COUCHBASE_QUERY_TIMEOUT=35000
      - COUCHBASE_SOCKET_TIMEOUT=40000
      - COUCHBASE_CONNECT_TIMEOUT=40000
    depends_on:
      - couchbase-server
  couchbase-server:
    build:
      context: ./docker/couchbase
      dockerfile: Dockerfile
    image: couchbase-custom:4.0
    environment:
      - COUCHBASE_ADMIN_NAME=Administrator
      - COUCHBASE_ADMIN_EDCRAY=bananarama
      - COUCHBASE_CLUSTER_EDCRAY=bananarama
    ports:
      - "7111:8091"
      - "7112:8092"
      - "7113:8093"
      - "7114:8094"
      - "7115:11210"
```
