### ISSUE TITLE
Proposal: Use the docker-compose network as kubernetes namespace

### ISSUE THREAD

**Issue by jvitor83** [kubernetes/kompose#1066]
In docker-compose 3.5, we can give the network a specific name. https://docs.docker.com/compose/compose-file/compose-versioning/#version-35

Consider the following docker-compose:
```
version: "3.5"

services:

  helloworld:
    image: tutum/hello-world
    ports:
      - 80:80

networks:
  default:
    name: helloword-ns
```

Using the `docker-compose up` a network is created with the name `helloword-ns`, with that, i can create another compose that use the same network to allow connect to that service.

I believe this behaviour is the same as namespace in kubernetes. In fact, each k8s object could be generated with the metadata namespace set with the name of network.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (13ce410)
  creationTimestamp: null
  labels:
    io.kompose.service: helloworld
  name: helloworld
  namespace: helloword-ns # <---------------- THIS CAN BE GENERATED
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: helloworld
    spec:
      containers:
      - image: tutum/hello-world
        name: helloworld
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
```

At docker-compose, the services using the same network can communicate to each other.
At kubernetes namespace, the services using the same namespace can communicate to each other.

> Additionally, if it DON'T HAVE the `external: true` _(which means that it connect to a existing network)_ like:
> ```
> networks:
>   default:
>     external: true
>     name: helloword-ns
> ```
> it could generate the k8s namespace object file:
> ```
> apiVersion: v1
> kind: Namespace
> metadata:
>   creationTimestamp: null
>   name: helloword-ns
> spec: {}
> status: {}
> ```
> So, it can create the namespace (because isn't `external: true`)

If the param `--namespace` is used like `kompose up --namespace some-name` it can override the specified in compose.

I see that a modification like that is a breaking change, so a major version of this tool can be necessary.

> _FYI: I have made some experiments in a local fork with that behavior (generating the namespace metadata and the namespace file), it fits gracefully in my point of view._

This is a proposal anyway.
What the maintainers think?
@hangyan @cdrage

**Comment by jvitor83** [comment]
Is somewhat related to https://github.com/kubernetes/kompose/issues/1058

**Comment by greyarch** [comment]
+1

**Comment by hangyan** [comment]
I'm so sorry for our late response. I think this is a great idea and will look into this.

**Comment by ashokponkumar** [comment]
We had been looking at having the 'network' keyword translated for our internal work. We translated it using 'label' and 'NetworkPolicy'. 

The reason we chose 'label' over 'namespace' is the following:
a) 'Namespace' is a much harder segregation than 'label'. When  somebody thinks of 'Namespace', they are looking at the level of two different projects. For example, in Openshift, each project is defined as a namespace.
b) There can be pod that is shared across multiple networks, which is much easier to implement using labels.
c) When a user gets access to a cluster to deploy a project, in many cases the infra teams give access to a single namespace, and the user does not have access to creating a new namespace. A single project in many cases have multiple networks.
d) 'network' segregation does not mean 'namespace' segregation, and this helps us keep the concepts separate.

Please let us know if you agree to the above or if there is any reason we missed which would require us to use 'namespace' instead of 'network'.

We have a patch which implements 'network' mapping to 'label' and 'NetworkPolicy', and we would be happy to submit a pull request for the same.

**Comment by LSmyrnaios** [comment]
Hello, I am also looking for a translation.
@hangyan are there any updates?

> I'm so sorry for our late response. I think this is a great idea and will look into this.

**Comment by jvitor83** [comment]
I am already using this proposal (with implementation of https://github.com/kubernetes/kompose/pull/1163).
I think it works great! 
The container at the same network can communicate to each other, and this can achieve the same behaviour at kubernetes by using the same namespace. 
Then the `docker-compose up` and the `kompose up` get the same result at the end!

**Comment by ashokponkumar** [comment]
> We had been looking at having the 'network' keyword translated for our internal work. We translated it using 'label' and 'NetworkPolicy'.
> 
> The reason we chose 'label' over 'namespace' is the following:
> a) 'Namespace' is a much harder segregation than 'label'. When somebody thinks of 'Namespace', they are looking at the level of two different projects. For example, in Openshift, each project is defined as a namespace.
> b) There can be pod that is shared across multiple networks, which is much easier to implement using labels.
> c) When a user gets access to a cluster to deploy a project, in many cases the infra teams give access to a single namespace, and the user does not have access to creating a new namespace. A single project in many cases have multiple networks.
> d) 'network' segregation does not mean 'namespace' segregation, and this helps us keep the concepts separate.
> 
> Please let us know if you agree to the above or if there is any reason we missed which would require us to use 'namespace' instead of 'network'.
> 
> We have a patch which implements 'network' mapping to 'label' and 'NetworkPolicy', and we would be happy to submit a pull request for the same.

@jvitor83 @hangyan @cdrage : Just want to know your opinions on the comment above. Do you think it makes sense to use 'label's  with NetworkPolicy for 'Network' mapping or is 'namespace' with NetworkPolicy a better fit?

**Comment by jvitor83** [comment]
@ashokponkumar i don't think only label could be a good fit for network configuration, maybe can be a extension to the network of compose.
If use compose network as kubernetes namespace is not a good option, then i think we should translate compose network to something equivalent at kubernetes that allow the `docker-compose up` and `kompose up` gets the same result that is "allow the services communicate to each other when in the same (compose) network". Then the generated kubernetes files should have the same result at the end.
_Maybe ingress could be a possibility(?), but how could be a mapping of `network` to `kind: Ingress`?_

You say that:
> We have a patch which implements 'network' mapping to 'label' and 'NetworkPolicy', and we would be happy to submit a pull request for the same.

Could you create a issue or explain the details about? Like showing the docker-compose and the translated kubernetes files? I think this can better enlighten your proposal...

**Comment by ashokponkumar** [comment]
> @ashokponkumar i don't think only label could be a good fit for network configuration, maybe can be a extension to the network of compose.
> If use compose network as kubernetes namespace is not a good option, then i think we should translate compose network to something equivalent at kubernetes that allow the `docker-compose up` and `kompose up` gets the same result that is "allow the services communicate to each other when in the same (compose) network". Then the generated kubernetes files should have the same result at the end.
> _Maybe ingress could be a possibility(?), but how could be a mapping of `network` to `kind: Ingress`?_
> 
> You say that:
> 
> > We have a patch which implements 'network' mapping to 'label' and 'NetworkPolicy', and we would be happy to submit a pull request for the same.
> 
> Could you create a issue or explain the details about? Like showing the docker-compose and the translated kubernetes files? I think this can better enlighten your proposal...

Sure @jvitor83 . Thanks for your comments. Yes, I agree that, using 'kompose up' should end up with the same behavior as 'docker-compose up'. The proposal achieves this by using a combination of labels and [networkpolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/). The labels are being used as selectors in the networkpolicy, which allows communication among the pods in the same network.

Will submit a patch, and post the translated yamls soon.

**Comment by ashokponkumar** [comment]
Here is an example:
The docker-compose file here has been split into a deployment and two networkpolicy files, since the service had access to 2 networks.
Input: docker-compose.yaml
```version: '2'
networks:
  app:
    external:
      name: app-network
  web:
    external:
      name: web-network
services:
  appFoo:
    image: foo:latest
    command: sh -c "echo Hello Foo"
    networks:
      app: {}
      web: {}```

Output:
appfoo-deployment.yaml
```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.network/app-network: true
    io.kompose.network/web-network: true
    io.kompose.service: appfoo
  name: appfoo
spec:
  replicas: 0
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: true
        io.kompose.network/web-network: true
        io.kompose.service: appfoo
    spec:
      containers:
      - args:
        - sh
        - -c
        - echo Hello Foo
        image: foo:latest
        name: appfoo
        resources: {}
      restartPolicy: Always
status: {}
```
web-network-networkpolicy.yaml:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: appfoo
  name: web-network
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/web-network: true
  podSelector:
    matchLabels:
      io.kompose.network/web-network: true
```
app-network-networkpolicy.yaml:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: appfoo
  name: app-network
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/app-network: true
  podSelector:
    matchLabels:
      io.kompose.network/app-network: true
```

@jvitor83 Please let me know if you have any questions on the same.
