### ISSUE TITLE
Duplicate container ports if different host ports point to same container port

### ISSUE THREAD

**Issue by dkarlovi** [kubernetes/kompose#1070]
If you have something like this:

```yaml
version: '3'
services:
    test:
        image: alpine
        ports:
        - '8000:80'
        - '80:80'
```

you end up with this:

```yaml
- apiVersion: extensions/v1beta1
  kind: Deployment
  spec:
    template:
      spec:
        containers:
        - image: alpine
          name: test
          ports:
          - containerPort: 80
          - containerPort: 80
```

which creates problems with usage on K8s.
