### ISSUE TITLE
Labels not converted to annotations in ingress

### ISSUE THREAD

**Issue by dkarlovi** [kubernetes/kompose#1071]
If you have something like:

```yaml
version: '2'
services:
    web:
        labels:
            kompose.service.expose: dev.example.com
            kompose.service.expose.tls-secret: tls-secret
            kompose.service.type: clusterip

            kubernetes.io/ingress.class: nginx
            certmanager.k8s.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/rewrite-target: /
        ports:
            - '80:80'
```

the annotations related to the ingress controller are not present in the `Ingress` object (they're there in `Service` and `Deployment`).
