### ISSUE TITLE
Environment variables of multiple docker-compose are not merged

### ISSUE THREAD

**Issue by bnoeson** [kubernetes/kompose#1081]
Hi,

I have 2 docker-compose files, where I put different environment variables. When I make a `kompose -f file1 -f file2 convert`, the variables are not merged, it just takes the environment variables of file2.

I have found some issues talking about that, but it seems that it is not yet fixed in 1.17.0.

Reproduction steps : 

docker-compose.yml
```
version: '3'
services:
  hello:
    image: helloworld
    environment:
      - VAR=whatever
```
docker-compose.prod.yml
```
version: '3'
services:
  hello:
    environment:
      - APP_ENV=prod
```

`kompose -f docker-compose.yml -f docker-compose.prod.yml convert`

hello-deployment.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe -f docker-compose.yml -f docker-compose.prod.yml
      convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: hello
  name: hello
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hello
    spec:
      containers:
      - env:
        - name: APP_ENV
          value: prod
        image: helloworld
        name: hello
        resources: {}
      restartPolicy: Always
status: {}
```

Desired behavior : in env, it should have 2 values

- ADD_ENV from docker-compose.prod.yml
- VAR from docker-compose.yml.
