### ISSUE TITLE
How do I use a service account?

### ISSUE THREAD

**Issue by skofgar** [kubernetes/kompose#1088]
I have a service account that I would like to use. I am able to use the service account's secret to connect to the cluster but when I use `kompose up` it publishes it under the default service account. 

I need it to use the service account I added, because that one also has the docker credentials for a private container repo.

Alternatively I found out that I can have kompose create the kubernetes files, and then I just manually add `spec.template.spec.serviceAccountName` to the yaml. Using `kubectl apply -f mydeployyaml.yaml` then successfully deploys the pod and k8s is able to pull from the private registry.  e.g.:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: myapp
  name: myapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myapp
    spec:
      containers:
      - image: myprivateregistry.url.com/myapp:snapshot
        name: eventbus
        ports:
        - containerPort: 8087
        - containerPort: 8088
        resources: {}
      restartPolicy: Always
      serviceAccountName: my-custom-ci-account  # <==== if I have this line everything is fine
status: {}
```

also my service account:

```
> kubectl get serviceaccounts my-custom-ci-account -o yaml 
apiVersion: v1
imagePullSecrets:
- name: my-custom-ci-account-artifactory-secret
kind: ServiceAccount
```

Please let me know if you see what I am doing wrong. Thank you for your time.
