### ISSUE TITLE
HostPath volumes incorrectly concatenate paths

### ISSUE THREAD

**Issue by willseward** [kubernetes/kompose#1089]
When using `--volumes hostPath`, the path of the volume (at least on macOS) incorrectly concatenates the full path of the docker-compose.yml file to the full path of the host mount:

Current:
```yaml
volumes:
      - hostPath:
          path: /Users/foobar/Documents/Projects/x/Users/foobar/Documents/Projects/x/runtime-media/mysql
        name: mysql-hostpath0
```

Expected:
```yaml
volumes:
      - hostPath:
          path: /Users/foobar/Documents/Projects/x/runtime-media/mysql
        name: mysql-hostpath0
```

See: https://github.com/kubernetes/kompose/pull/957/
