### ISSUE TITLE
Volumes path with underline was converted into dash

### ISSUE THREAD

**Issue by ChenTanyi** [kubernetes/kompose#1094]
When I convert a docker-compose.yml file, the volumes path with underline will change into dash.

Simple example:
```yaml
version: "2"
services:
  hello:
    image: hello-world
    volumes:
      - ./hello_world:/hello_world
```
It will be converted into
```yaml
      containers:
      - image: hello-world
        name: hello
        resources: {}
        volumeMounts:
        - mountPath: /hello-world
          name: hello-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /Users/test/test/hello-world
        name: hello-hostpath0
```
All ```hello_world``` were converted into ```hello-world```

kompose verion: 1.17.0 (HEAD), go get from master currently (1-15, 2019)
os: mac os 10.13.4
