### ISSUE TITLE
'expose' is not converted

### ISSUE THREAD

**Issue by stevefan1999-personal** [kubernetes/kompose#1095]
Using this `docker-compose.yml` for example:
```yml
version: '3'
services:
    seafile:
        container_name: seafile
        image: seafileltd/seafile:latest
        volumes:
            - seafile:/shared
        restart: always
        expose:
            - 80/tcp
```
Does not generate
```yml
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
```
However, if I change `expose` to `ports`, it does, but it is contradictory to the conversion matrix.
