### ISSUE TITLE
Issues with volume mounts in docker-compose.yml

### ISSUE THREAD

**Issue by DevasiaThomas** [kubernetes/kompose#1097]
I have the following in my compose yml
```
volumes:
       - type: bind
         source: /var/run/docker.sock
         target: /var/run/docker.sock
       - type: bind
         source: /dev
         target: /host/dev
         read_only: true
         bind:
           propagation: rslave
       - type: bind
         source: /sys
         target: /host/sys
         read_only: true
         bind:
           propagation: rslave
       - type: bind
         source: /boot
         target: /host/boot
         read_only: true
         bind:
           propagation: rslave
       - type: bind
         source: /home
         target: /host/home
         read_only: true
         bind:
           propagation: rslave
       - type: bind
         source: /run
         target: /host/run
         read_only: true
         bind:
           propagation: rslave
       - type: bind/
         source: var
         target: /host/var
         read_only: true
         bind:
           propagation: rslave
       - type: bind
         source: /proc
         target: /host/proc
         read_only: true
         bind:
           propagation: rslave
```
When I try to convert it says "volume mount on the host is not supported".  But I thought it was supported through host paths. I read in some issue here that host path support was added. Am I doing something wrong here? I'm fine with editing generated files but I'm just dipping into k8s so I don't know what to edit in the generated files.
