### ISSUE TITLE
kompose up returning ErrImagePull while pulling from a private repo

### ISSUE THREAD

**Issue by tal47** [kubernetes/kompose#1102]
Hi all,
I have created (and pushed) a private docker hub repo, and created a secret using:

```
$ echo -n 'password' > ./password.txt
$ echo -n 'user' > ./username.txt
$ kubectl create secret generic docker-user-pass --from-file=./username.txt --from-file=./password.txt
secret/docker-user-pass created
```

Now, I have created a docker-compose.yml file:

```
version: '3.1'
services:
  statisticstest:
    build:
      context: ../ 
      dockerfile: nts/Dockerfile-StatisticsTest
    image: "<repo>/<name>:1.0"
    secrets:
      - docker-user-pass
secrets:
  docker-user-pass:
    external: true
```

While running ```kompose up``` I'm getting the desired ```Your application has been deployed to Kubernetes. ```
But when describing the pods, I am getting:

![screenshot from 2019-02-04 12-35-32](https://user-images.githubusercontent.com/16876322/52203562-331a6600-287a-11e9-957a-f6a82ac8d0ed.png)

As you can see, I am failing there when the secret should be called.

Any help? Thanks :)
