### ISSUE TITLE
error decoding 'Ports': No port specified: ::<empty>

### ISSUE THREAD

**Issue by avikjis27** [kubernetes/kompose#1104]
I am trying to convert (`kompose convert`) below docker compose file. Ihave tested the compose file is working fine with `docker-compose run iss-rabbit-mq`.
```
version: '3'
networks:
    mse:
services:
    iss-rabbit-mq:
        container_name: iss-rabbit-mq
        image: ${DOCKER_REPO}/iss-rabbit-mq:${RABBIT_MQ_VERSION}
        env_file:
            - ./.env
        ports:
            - "${RABBIT_MQ_PORT}:${RABBIT_MQ_PORT}"
            - "${RABBIT_MQ_MANAGEMENT_PORT}:${RABBIT_MQ_MANAGEMENT_PORT}"
        dns: ${LOCAL_DNS_ADDRESS}
        networks:
            - mse

```
Getting below error:
```
FATA 1 error(s) decoding:

* error decoding 'Ports': No port specified: ::<empty> 
```
The .env file is given below
```
DOCKER_REPO=artifactory.rds.xxx.com:5000
RABBIT_MQ_PORT=6379
RABBIT_MQ_MANAGEMENT_PORT=6060
LOCAL_DNS_ADDRESS=10.199.134.18
RABBIT_MQ_VERSION=latest
```
