### ISSUE TITLE
Support yaml anchors

### ISSUE THREAD

**Issue by paranoidi** [kubernetes/kompose#1155]
Docker-compose enables DRY by using yaml anchors.

```
x-projectname-py: &projectname-py
  environment:
    - DB_NAME=dev
    - DB_USER=django
    - DB_PASSWORD=django
    - DB_HOST=mariadb
    - DB_PORT=3306
    - PYTHONUNBUFFERED=1
  depends_on:
    - mariadb
    - redis
    - rabbitmq
  volumes:
    - .:/mnt

services:
  some-service-name:
    <<: *x-projectname-py
    # normal service configuration
```

Unfortunately kompose validation prevents this being used.

`FATA x-projectname-py Additional property x-projectname-py is not allowed`

I think docker-compose validation ignores keys with `x-` prefix from root. Kompose should do the same.
