### ISSUE TITLE
bug: docker configs object filepath error

### ISSUE THREAD

**Issue by johncming** [kubernetes/kompose#1157]
https://github.com/kubernetes/kompose/blob/7b6c89b3defa0962989d52c7b82efb55117daa2c/pkg/transformer/kubernetes/k8sutils.go#L631-L632

directory  is repeat.

FATA Unable to retrieve file: Unable to read file: open /Users/john/example-prometheus/Users/john/example-prometheus/prometheus.yaml: no such file or directory .

**Comment by Verneri** [comment]
Just noticed the same problem. it is rather annoying as it makes it impossible to use configs

**Comment by adamelliotfields** [comment]
A workaround is prefixing the config file with a forward slash. Since `path.Join()` calls `path.Clean()` automatically, the result will be the absolute path to your config file without the duplicate directory name.

If `docker-compose.yml` and `nginx.conf` are in the same directory:

```yaml
services:
  nginx:
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf

configs:
  nginx.conf:
    file: /nginx.conf
```

**Comment by hangyan** [comment]
i think #1175 fix this

**Comment by hangyan** [comment]
@adamelliotfields @Verneri You can give the latest master try if you don't mind, many thanks!

**Comment by adamelliotfields** [comment]
Hey @hangyan sorry for the late reply!

I just built from `master` and it's working now!

```bash
touch nginx.conf

cat <<EOF > docker-compose.yml
version: '3.7'
services:
  nginx:
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
        mode: 0444
configs:
  nginx.conf:
    file: ./nginx.conf
EOF

~/.go/src/github.com/kubernetes/kompose convert

# INFO Kubernetes file "nginx.conf-configmap.yaml" created
# INFO Kubernetes file "nginx-deployment.yaml" created
```

**Comment by pse-sonic** [comment]
@adamelliotfields Have you tried to deploy the files?

My tests show up that #1175 causes a modification of the specified target. k8sutils#FormatFileName extracts the filename and drops the path so the resulting MountPath differs from specified target.

**Comment by adamelliotfields** [comment]
Good catch. Truthfully, I did not try to deploy. I've only ever used Kompose as a scaffolding tool to generate some starter yaml files.

Here's the generated yaml from my previous comment (you'll see it mounts `nginx.conf` to to `/`, not `/etc/nginx`:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/adam.fields/.go/src/github.com/kubernetes/kompose/kompose
      convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/adam.fields/.go/src/github.com/kubernetes/kompose/kompose
          convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /nginx.conf
          name: nginx.conf
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 292
          name: nginx.conf
        name: nginx.conf
status: {}
```

Also worth mentioning with Kubernetes 1.16, the API group and version for a Deployment is `apps/v1`.
