### ISSUE TITLE
convert the 2.1 version docker-compose.yaml  error!!!!!

### ISSUE THREAD

**Issue by hicker-kin** [kubernetes/kompose#1235]
when convert :
kompose convert -f docker-compose.yaml, it is error：
FATA Version 2.1 of Docker Compose is not supported. Please use version 1, 2 or 3 . The follow is my yaml file:

version: '2.1'
services:
  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: 172.46.5.78:332/library/sqshq/piggymetrics-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

thanks for your answer.

**Comment by hicker-kin** [comment]
my kompose version is v1.20.0 .  If i exchange the version of docker-compase to "version: '2'",the error is "Service 'registry' configuration key 'depends_on' contains an invalid type, it should be an array."

**Comment by hangyan** [comment]
@hicker-kin Could you provide a well-formed version of this compose file?

**Comment by Jellyfrog** [comment]
Here is an example
```
version: '2.1'
services:
  testbar:
    image: example/testbar:latest
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=testbar
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=testbar
    healthcheck:
      test: "mysqladmin ping -h localhost"
      timeout: 5s
      retries: 10
    command: mysqld --lower_case_table_names=1
    ports:
      - "3306"
  testfoo:
    image: example/testfoo:latest
    ports:
      - "8081"
    links:
      - "testbar:testbar_SERVER"

```

**Comment by luckydonald** [comment]
Yeah, `2.1` should be supported too.

**Comment by mdrobniu** [comment]
`# kompose convert`
`FATA Version 2.1 of Docker Compose is not supported. Please use version 1, 2 or 3`
`]# kompose version`
`1.21.0 (992df58d8)`
`#`

```
cat docker-compose.yml
---
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
```
Anyidea what I'm doing wrong?

**Comment by mdrobniu** [comment]
Okay I've fixed by changing the version in the yaml file to "3"

**Comment by luckydonald** [comment]
It's not fixed that way, it's only a workaround.

I have about 20 docker compose files, so that's really no fun...

**Comment by atul10864** [comment]
when convert :
kompose -f ../docker-compose.yml convert -y, it is error
Flag --yaml has been deprecated, YAML is the default format now.
FATA Version 2.1 of Docker Compose is not supported. Please use version 1, 2 or 3

 The follow is my yaml file:
version: '2.1'
services:

    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:1.9.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
            - storage-proxy

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:2.3.1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        environment:
            - GATEWAY_IP
            - INTEGRATION_VERSION
            - MENDER_ARTIFACT_VERSION
            - MENDER_VERSION
            - MENDER_DEB_PACKAGE_VERSION

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:2.1.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-deployments
            - mender-gui
            - mender-useradm
            - mender-inventory

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:2.2.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
            - mender-conductor

    #
    # mender-inventory
    #
    mender-inventory:
        image: mendersoftware/inventory:1.7.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-useradm
    #
    mender-useradm:
        image: mendersoftware/useradm:1.10.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-workflows
    #
    mender-workflows-server:
        image: mendersoftware/workflows:1.0.0
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-create-artifact-worker
    #
    mender-create-artifact-worker:
        image: mendersoftware/create-artifact-worker:1.0.1
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        environment:
            - WORKFLOWS_MONGO_URL=mongodb://mongo-workflows:27017
            - CREATE_ARTIFACT_GATEWAY_URL=https://mender-api-gateway
            - CREATE_ARTIFACT_DEPLOYMENTS_URL=http://mender-deployments:8080
        networks:
            - mender
        depends_on:
            - mender-mongo

    mender-mongo:
        image: mongo:3.6
        extends:
            file: common.yml
            service: mender-base
        networks:
            mender:
                aliases:
                    - mongo-tenantadm
                    - mongo-deployments
                    - mongo-device-auth
                    - mongo-inventory
                    - mongo-useradm
                    - mongo-workflows

    mender-conductor:
        image: mendersoftware/mender-conductor:1.6.0
        depends_on:
            - mender-elasticsearch
            - mender-redis
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

    mender-elasticsearch:
        image: elasticsearch:6.8.6
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - network.host=0.0.0.0

    mender-redis:
        image: redis:5-alpine3.8
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

networks:
    mender:

Need suggestion about this error thanks in advance for your valuable suggestion.

**Comment by hangyan** [comment]
@atul10864 @luckydonald I am so sorry guys, this is due to the docker/libcompose we rely on, it's old and not maintained anymore. I am trying to upgrade our go mod to use the latest version of it. Seems promising.

**Comment by hangyan** [comment]
Feel free to reopen this issue if it's not working

**Comment by mohammed-cs8** [comment]
@hangyan the same issue still happen for v2.2

```
kompose convert -f docker-compose.yml
FATA Version 2.2 of Docker Compose is not supported. Please use version 1, 2 or 3
```
`kompose version` `1.22.0 (955b78124)`

docker-compose.yml:
```
version: "2.2"

services:

### Workspace ###
  workspace:
    image: localhost/blazecms-workspace:latest
    build:
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_EMAIL=${GIT_EMAIL}
    volumes:
      - ${APPLICATION}:/var/www
    tty: true
    ports:
      - "3000:5802"
      - "3001:5803"
    restart: always

### MySQL ###
  mysql:
    build:
      context: ./mysql
    volumes:
      - ${APPLICATION}:/var/www
      - ${DATA}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    mem_limit: 250m

### PHP-FPM 7.2 ###
  php-fpm7.2:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=7.2.16
    volumes:
      - ${APPLICATION}:/var/www
    restart: always
```
