### ISSUE TITLE
[BUG] Repeated resources in YAML file when --out flag is supplied

### ISSUE THREAD

**Issue by jbmcfarlin31** [kubernetes/kompose#1239]
## What is happening?
When converting the following docker-compose file:
```yaml
version: '3'
networks:
  int:
    external:
      name: int-network
services:
  emailservice:
    image: gcr.io/google-samples/microservices-demo/emailservice:v0.1.3
    hostname: emailservice
    restart: always
    ports:
      - '5000:8080'
    networks:
      int: {}
    environment:
      - PORT=8080
      - ENABLE_PROFILER=0
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  checkoutservice:
    image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.1.3
    hostname: checkoutservice
    restart: always
    ports:
      - '5050:5050'
    networks:
      int: {}
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  recommendationservice:
    image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.1.3
    hostname: recommendationservice
    restart: always
    ports:
      - '5353:8080'
    networks:
      int: {}
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - ENABLE_PROFILER=0
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 450M
        reservations:
          cpus: '0.1'
          memory: 220M
  frontend:
    image: gcr.io/google-samples/microservices-demo/frontend:v0.1.3
    hostname: frontend
    restart: always
    ports:
      - '80:8080'
    networks:
      int: {}
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:5353
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  paymentservice:
    image: gcr.io/google-samples/microservices-demo/paymentservice:v0.1.3
    hostname: paymentservice
    restart: always
    ports:
      - '50051:50051'
    environment:
      - PORT=50051
    networks:
      int: {}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  productcatalogservice:
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.1.3
    hostname: productcatalogservice
    restart: always
    ports:
      - '3550:3550'
    environment:
      - PORT=3550
    networks:
      int: {}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  cartservice:
    image: gcr.io/google-samples/microservices-demo/cartservice:v0.1.3
    hostname: cartservice
    restart: always
    ports:
      - '7070:7070'
    networks:
      int: {}
    environment:
      - PORT=7070
      - REDIS_ADDR=redis-cart:6379
      - LISTEN_ADDR=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 64M
  loadgenerator:
    image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.1.3
    hostname: loadgenerator
    restart: always
    networks:
      int: {}
    environment:
      - FRONTEND_ADDR=frontend:80
      - USERS=10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M
  currencyservice:
    image: gcr.io/google-samples/microservices-demo/currencyservice:v0.1.3
    hostname: currencyservice
    restart: always
    ports:
      - '7000:7000'
    networks:
      int: {}
    environment:
      - PORT=7000
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  shippingservice:
    image: gcr.io/google-samples/microservices-demo/shippingservice:v0.1.3
    hostname: shippingservice
    restart: always
    ports:
      - '50051:50051'
    networks:
      int: {}
    environment:
      - PORT=50051
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  redis-cart:
    image: redis:alpine
    hostname: redis-cart
    restart: always
    ports:
      - '6379:6379'
    networks:
      int: {}
    tmpfs:
      - /data
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 256M
        reservations:
          cpus: '0.07'
          memory: 200M
  adservice:
    image: gcr.io/google-samples/microservices-demo/adservice:v0.1.3
    hostname: adservice
    restart: always
    ports:
      - '9555:9555'
    networks:
      int: {}
    environment:
      - PORT=9555
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 180M
```
Using the command: `kompose convert -f docker-compose.yaml -o kompose.yaml`
One file named `kompose.yaml` is generated, and slew of output from the `kompose` command is given:
```bash
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network int-network is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
```

This appears to be okay and convert fine... however, when attempting to perform a `kustomize` on that one generated `kompose.yaml` file, errors occur such as:
```bash
Error: accumulating resources: accumulating resources from 'kompose.yaml': may not add resource with an already registered id: extensions_v1beta1_NetworkPolicy|~X|int-network
```

Upon inspecting the `kompose.yaml` file, there are 11 (maybe 12) repeated instances of:
```yaml
- apiVersion: extensions/v1beta1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: null
    name: int-network
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            io.kompose.network/int-network: "true"
    podSelector:
      matchLabels:
        io.kompose.network/int-network: "true"
```

However, if you do NOT supply the `--out` flag to the command: `kompose convert -f docker-compose.yaml`

You get individual YAML files generated for each service defined in the docker-compose file, and only one YAML file for the `int-network-network-policy` resource.

If I take all of those individual files, and concat them into a single file separating each yaml doc with `---`, then perform the `kustomize` command - I get a successful kustomization. It is worth noting that our `kustomization.yaml` is nothing special, all it consists of is:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- kompose.yaml
```
Where the `kompose.yaml` is the file created by the `kompose convert` command.

## What did you expect to happen?
Same behavior between `kompose convert -o` versus `kompose convert`.
