### ISSUE TITLE
Labels are not passed as annotations when creating a Pod

### ISSUE THREAD

**Issue by opdude** [kubernetes/kompose#1247]
It seems that if you set a restart policy that is not always a Pod is created, however, annotations are then not moved over to the Pod. Is that expected?

Docker-compose example
```
version: '3.7'
services:
  migrate:
    image: my-image:test
    restart: "on-failure"
    labels:
       test.annotate: test
```

Example-ouput
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  containers:
  - image: my-image:test
    name: migrate
    resources: {}
  restartPolicy: OnFailure
status: {}
```

```
❯ kompose version                                                               ─╯
1.20.0 ()
```
