### ISSUE TITLE
Kompose not creating pods & deployments on minikube

### ISSUE THREAD

**Issue by syahrul12345** [kubernetes/kompose#1264]
Hey guys, I'm new to kompose and trying to set up the example project using the `docker-compose.yaml` file provided in the getting started page.

```
version: "3"

services:

  redis-master:
    image: k8s.gcr.io/redis:e2e 
    ports:
      - "6379"

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    ports:
      - "6379"
    environment:
      - GET_HOSTS_FROM=dns

  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer
```

Running `kompose up` deploys the services to my minikube cluster. However, it seems that doing so doesn't create the any pods, so when i run `minikube service frontend` i get a `this site cant be reached` error in my browser.

Running `kubectl get pods` and `kubectl get deploy` shows empty.

Is this intended? 

My current workaround is to simply run
` kompose convert && kubectl apply -f . `

I would prefer not to do this, as it creates yaml files that makes the project directory pretty messy.
