### ISSUE TITLE
.env file creates -env entries, no ConfigMap

### ISSUE THREAD

**Issue by vertti** [kubernetes/kompose#1267]
I have an `.env` file like this:

```
TWITTER_CONSUMER_KEY=replaced
TWITTER_CONSUMER_SECRET=replaced
COINMARKETCAP_KEY=replaced
```
and a `docker-compose.yaml` like this:
```
version: '2'

services:
  redis:
    image: redis
    expose:
      - 6379

  writer:
    build:
      context: ./
      dockerfile: Dockerfile-writer
    env_file: .env
    links: 
      - redis

  reader:
    build:
      context: ./
      dockerfile: Dockerfile-reader
    env_file: .env
    links: 
      - redis
    ports: 
      - "5000:5000"
```

Now, I would expect `kompose convert` to create a `ConfigMap` definition that would be referenced in each deployment descriptor. Instead I get a misleading error message:
```
WARN Unsupported env_file key - ignoring          
INFO Kubernetes file "reader-service.yaml" created 
INFO Kubernetes file "redis-service.yaml" created 
INFO Kubernetes file "reader-deployment.yaml" created 
INFO Kubernetes file "redis-deployment.yaml" created 
INFO Kubernetes file "writer-deployment.yaml" created 
```
and each deployment contains env entries like this:

```
    spec:
      containers:
      - env:
        - name: COINMARKETCAP_KEY
          value: replaced
        - name: TWITTER_CONSUMER_KEY
          value: replaced
        - name: TWITTER_CONSUMER_SECRET
          value: replaced
        image: reader
        imagePullPolicy: ""
        name: reader
```
