### ISSUE TITLE
--build build-config wipes image streams

### ISSUE THREAD

**Issue by vertti** [kubernetes/kompose#1285]
I have a setup which has my own container built from Dockerfiles and Kafka that is used from known image.

When I run `kompose --provider=openshift convert` the `kafka1-imagestream.yaml` has:

```
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: confluentinc/cp-kafka:5.5.0
    generation: null
    importPolicy: {}
    name: 5.5.0
```

but when I re-run it with `kompose --provider=openshift --build build-config convert`, the same kafka image stream is wiped empty spec to:

```
spec: {}
```
