### ISSUE TITLE
Unable to read env_file that works with docker-compose up

### ISSUE THREAD

**Issue by jongio** [kubernetes/kompose#1287]
I have this structure: .env is in the root, docker-compose is two levels deep.

/root/.env
/root/src/net/docker-compose.yml

In docker-compose.yml, I reference the .env file like this:

```
  azsdkdemoapi:
    image: azsdkdemoapi
    env_file: ../../.env
    build:
      context: .
      dockerfile: Api/Dockerfile
```

This works when I run docker-compose up.

If I run kompose convert, I get the following:
`←[31mFATA←[0m Unable to retrieve env file: Unable to read env_file: open ../.env: The system cannot find the file specified. `

I've tried this in Git Bash, WSL, and Windows CMD.

It only works if the .env file is at the same level as the docker-compose file.

azsdke2e
