### ISSUE TITLE
Support the `.env` file in `kompose convert -f docker-compose.yml`

### ISSUE THREAD

**Issue by miso-belica** [kubernetes/kompose#1289]
Hello,

I would like to ask for the support of the `.env` files when converting `docker-compose.yml` file to Kubernetes/OpenShift files. When I try to convert the file I get the error `FATA 1 error(s) decoding: error decoding 'Ports': No port specified: ::<empty>`. I found the issue https://github.com/kubernetes/kompose/issues/1104 describing the problem but it was closed for the inactivity. I believe the problem was the same there.

Also, I found the workaround in the article [Use Kompose to convert docker-compose.yaml but got an error decoding 'Ports'](https://www.andretw.com/2019/09/use-kompose-to-convert-docker-compose-yaml-but-got-an-error.html). The advice there is to do `docker-compose config > docker-compose.openshift.yml` 1st and then `kompose convert -f docker-compose.openshift.yml --provider=openshift`. That works but has a side-effect of creating files with the hard-coded values instead of splitting them to config maps and other files.

Here are the minimal files to reproduce it with the command `kompose convert -f docker-compose.yml --provider=openshift`. The command exits with the error above even if it is defined in the `.env` file where all ENV variables are correctly defined.

```yaml
# this is docker-compose.yaml file
version: '3.4'
services:
    goodbot:
        image: python
        env_file:
            - .env
        ports:
            - ${PORT}:${PORT}

```

```
# this is .env file
PORT=123
```

Thanks in advance for the response :)
