### ISSUE TITLE
[BUG] Kompose doesn't read config from URL

### ISSUE THREAD

**Issue by jbmcfarlin31** [kubernetes/kompose#1291]
When using configs with a compose file, you can specify a `file` attribute for where the config lives. For example:
```yaml
configs:
  conf1:
    name: testconfigfile
    file: ./testconfigfile.conf
```

This is expecting that the file exists on the machine that is running docker-compose presumably. However, if you specify a url to the config file instead, it breaks as it does not follow the url but rather just appends:
```yaml
configs:
  conf1:
    name: testconfigfile
    file: "https://repo.example.com/mygroup/myproject/-/raw/master/testconfigfile.conf" 
```
Results in:
```
FATA Unable to retrieve file: Unable to read file: open /tmp/compose/https://repo.example.com/mygroup/myproject/-/raw/master/testconfigfile.conf: no such file or directory
```

I would expect that `kompose` would fetch the config from the URL and then apply whatever it does to it.
