### ISSUE TITLE
Ports are parsed incorrectly from "expose"

### ISSUE THREAD

**Issue by karimsa** [kubernetes/kompose#1321]
Using the following compose file:

```
version: "3"
services:
  blah:
    image: alpine
    expose:
    - 53:53/udp
```

The output for the port specification is:

```
 spec:
    ports:
    - name: "0"
      port: 0
      protocol: UDP
      targetPort: 0
```

Interestingly enough, if I use "ports" instead of "expose" in the compose file, then the output is correct.
