### ISSUE TITLE
Add prefix or suffix to service's metadata name

### ISSUE THREAD

**Issue by qaifshaikh** [kubernetes/kompose#1327]
This is my `docker-compose.yml`
```
services:
  redis-master:
    image: k8s.gcr.io/redis:e2e
    ports:
      - "6379"
    container_name: redis-master-abc
```
And this is the converted `redis-master-service.yml`
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-master
status:
  loadBalancer: {}
```

I'm wondering if we can have the option to add prefixes or suffixes like hostname variables to the metadata and others like this:
```
metadata:
  labels:
    io.kompose.service: redis-master-abcxyz
  name: redis-master-abcxyz
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-master-abcxyz
```

Is this something that can be done? If not, why is it a bad idea to do so?
