### ISSUE TITLE
[Question] Can kubernets recreate your images from a dockerfile?

### ISSUE THREAD

**Issue by seanybaggins** [kubernetes/kompose#1360]
I am a complete beginner to Kubernetes.

Suppose I am using the`buildconfig` example but slightly modified.
```
.
├── build
│   └── Dockerfile
└── docker-compose.yml
```

Dockerfile
```Dockerfile
FROM busybox:1.26.2

RUN touch /test

```

docker-compose.yml
```yaml
version: "2"

services:
  foo:
    build: 
       context: "./build"
    container_name: bar
```

When I run `kompose convert` I get the following generated file.

foo-deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: foo
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: foo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: foo
    spec:
      containers:
        - image: foo
          name: bar
          resources: {}
      restartPolicy: Always
status: {}
```

I thought the generated file would have some reference/context to the Dockerfile but I don't see any. Is there something I am missing or is kubernetes unable to build from a Dockerfile?
