### ISSUE TITLE
Adding storageClassName to persistent volume claim manifest

### ISSUE THREAD

**Issue by sundayoyeniyi** [kubernetes/kompose#1362]
Hi

I have a persistent volume claim manifest file created from Kompose convert.  I noticed the manifest file is missing a storageClassName attribute that I will like to include.  Also, there is currently no kompose label that supports adding a storageClassName to the generated manifest file.  Could there be any way I could instruct Kompose convert to add storageClassName to the spec of a PVC instead of manually editing the file after it has been generated?

Kompose convert will generate the spec below in a PVC:
```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

But I will like the ability to configure it to generate the below:

```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: 'custom-storage-class-name'
```
