### ISSUE TITLE
Kompose convert fails on depends_on condition: service_healthy

### ISSUE THREAD

**Issue by DenisBalan** [kubernetes/kompose#1371]
After introducing `condition: service_healthy` in `depends_on` running `kompose convert` fails with
`FATA services.time-slot-hystrix-monitoring.depends_on must be a list` 
```
services:

  time-slot-turbine-stream-service:
    image: "denisbalan/turbine-stream-service"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep LISTEN"]
      interval: 10s
      timeout: 5s
      retries: 5
	  
  time-slot-hystrix-monitoring:
    depends_on:
      time-slot-turbine-stream-service:
        condition: service_healthy
    image: "denisbalan/hystrix-monitoring"
```
