### ISSUE TITLE
Experience report: converting librenms (and combining containers into a pod)

### ISSUE THREAD

**Issue by candlerb** [kubernetes/kompose#1390]
Firstly, I'd like to say that kompose is a wonderful tool and has already saved me a bunch of time.

I've just converted a docker-compose configuration for librenms, using kompose version `1.22.0 (955b78124)`, and there were a number of post-processing steps that I had to do.  I thought I'd document them here, in case there are some ideas for how kompose might work even better.

## Source data

The librenms docker-compose configuration is [here](https://github.com/librenms/docker/tree/master/examples/compose).  It comprises the following files:

* `.env`
* `docker-compose.yml`
* `librenms.env`
* `msmtpd.env`

kompose happily consumed the last three of these files, and generated a bunch of yaml files.  I tested using `k3s`.

## Shared data volumes

Three containers share the same data volume, as declared in the docker-compose.yml file:

```
services:
  ...
  librenms:
    ...
    volumes:
      - "./librenms:/data"
  ...
  dispatcher:
    ...
    volumes:
      - "./librenms:/data"
  ...
  syslogng:
    ...
    volumes:
      - "./librenms:/data"
```

However, kompose had created three separate pods and three separate PVCs for `/data`, so they were not shared.  In particular, the librenms dispatcher container checks for a file `/data/.env` created by the main librenms container, and terminates if it doesn't exist.

**What I did**: I merged the three containers into the same pod, and deleted the extra PVCs.  I also had to change the service selector for the syslogng service to select the combined (librenms) pod.

**What kompose might do**: if it sees multiple containers sharing the same source volume, it could combine them into a single pod, and create a single PVC for the shared volume.  The pod name would have to be chosen arbitrarily - e.g. it could be named after the first container seen.  (I think this is reasonable: people are likely to put the main container first, followed by the sidecars).

[EDIT: it doesn't necessarily need to stick the containers in the same pod, but if it doesn't, it would have to create the PVC as `ReadWriteMany`]

## Fixup environment variables from `.env`

The `.env` file has a number of declarations like this:

```
...
MYSQL_USER=librenms
MYSQL_PASSWORD=asupersecretpassword
```

and the docker-compose.yml file references them in several places like this:

```
    environment:
      ...
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
```

However, the generated yaml files from kompose produced empty declarations for these variables:

```
        - env:
            - name: DB_USER
            - name: DB_PASSWORD
```

**What I did:** I created a new "secret" object:

```
apiVersion: v1
kind: Secret
metadata:
  name: dotenv
data:
  ...
  MYSQL_USER: bGlicmVubXM=
  MYSQL_PASSWORD: YXN1cGVyc2VjcmV0cGFzc3dvcmQ=
type: Opaque
```

and I changed all the container environment variable references to use it:

```
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dotenv
                  key: MYSQL_USER 
           - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dotenv
                  key: MYSQL_PASSWORD
```

**What kompose might do:** [EDIT] I think kompose should process the `.env` file, as described in the docker-compose specification [here](https://docs.docker.com/compose/environment-variables/).

I was able to get this to work in a simplistic way by inserting "export" in front of each definition in `.env`, then sourcing it into the shell, then running kompose.  Then it substituted the values literally into the generated resources:

```
            - name: DB_USER
              value: librenms
            - name: DB_PASSWORD
              value: asupersecretpassword
```

However, the same environment values are substituted in multiple places, so I'd still have needed to go through to combine them back into a configMap or secret anyway.

In general, I think that it would be better for `.env` values (and any referenced free environment variables) to be captured by kompose into a configMap.  Then the values can be adjusted when deploying the resources, rather than being frozen directly into those resources.

I think it would be possible to for kompose to do this automatically, in a similar way to what it already does for direct `environment` definitions in docker-compose.yml.  It would be straightforward for the simple 1:1 substitutions used by librenms, but would be harder for compound expansions like `"DB_USER=${MYSQL_USER}@localhost"` [^1].

kompose could also give a warning when it tries to expand a `"${VARIABLE}"` which is unset.  However, it can still replace this with a reference to a configMap, with an empty value.

## Adding a "db" service

The librenms container accesses the database by using its name, "db".  This name resolution works between containers in docker-compose, but not in kubernetes unless you create a service.

**What I did:** I created a "db" service object

```
...
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: db
```

**What kompose might do:** Unfortunately I don't think it can do anything here, because the docker-compose.yml file doesn't declare that the db container exposes port 3306.  In theory it might be possible to introspect the container image, but that would involve communication with the registry.

Perhaps it should create a headless service on an arbitrary port for every container that doesn't have a service, "just in case".

## Fixing DB_PORT

When running, the librenms-dispatcher sidecar container was confused by DB_PORT.  It kept logging once per second:

```
invalid literal for int() with base 10: 'tcp://10.43.102.152:3306'
invalid literal for int() with base 10: 'tcp://10.43.102.152:3306'
invalid literal for int() with base 10: 'tcp://10.43.102.152:3306'
...
```

where 10.43.102.152 is the internal address of the "db" pod.  It turns out that Kubernetes was setting environment variable

`DB_PORT=tcp://10.43.102.152:3306`

but the container was trying to interpret that as a plain port number.

**What I did:** I forcibly set the environment variable in the podspec

```
        - env:
            - name: DB_PORT
              value: "3306"
```

**What kompose might do:** I don't think this can be fixed.  The docker-compose.yml file doesn't declare that the application is affected by an environment variable called DB_PORT, and it's an unfortunate accident that kubernetes sets it in a way that interferes with the application.  I don't see a way to tell k8s not to set these automatic environment variables.

## Miscellaneous

I decided to set a namespace by hand on all objects.  This isn't really an issue, because it could be delegated to some post-processing tool like kustomize.

I needed to add an ingress, and to adjust the PVC volume sizes.  I think it's perfectly reasonable to expect the user to do these steps: there's not enough info in docker-compose.yml to decide what to do.

## Conclusion

[EDIT] I think the main realistic takeaways for kompose are:
* to process the `.env` file
* to combine containers into a pod when they share a volume.

-----

[^1] Here's a possible solution:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotenv
data:
  MYSQL_USER: librenms
---
apiVersion: v1
kind: Pod
metadata:
  name: env-test
spec:
  containers:
  - name: printenv
    image: bash
    env:
    - name: ".MYSQL_USER"
      valueFrom:
        configMapKeyRef:
          name: dotenv
          key: MYSQL_USER
    - name: DB_USER
      value: "$(.MYSQL_USER)@localhost"
    command: ["printenv"]
```

Note that the ordering of the list under `env` is important: a defined env value is only available for substitution in subsequent env definitions.

This approach does also pollute the environment with additional, unneeded variables. Here I prefixed the name with dot to make it less likely to collide.  Better would be to use a strongly random prefix or name.
