### ISSUE TITLE
Please support docker-compose-wait

### ISSUE THREAD

**Issue by patsevanton** [kubernetes/kompose#1392]
Hello! Thanks for kompose!
I try transfer docker-compose to kubernetes.
Some docker-compose files have WAIT_HOSTS using by https://github.com/ufoscout/docker-compose-wait.
Please support docker-compose-wait in kompose.
Thanks!

**Comment by raphaelauv** [comment]
that would mean translate any WAIT_HOSTS by a initContainer https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by patsevanton** [comment]
I use:
```
      initContainers:
        - name: wait-for-drill-admin-service
          image: groundnuty/k8s-wait-for:v1.3
          args:
            - "service"
            - "-lapp.kubernetes.io/name=XXXX"
```
