### ISSUE TITLE
Support multiple types of volumes

### ISSUE THREAD

**Issue by jlevertov** [kubernetes/kompose#1400]
Hi,
I have a question.
I have a docker-compose.yml file in which there are 2 types of volumes:
* Json files that should be mounted as configmaps.
* Just emptydirs that serve as a temp storage for runtime.
My question is: Is it possible to convert such a docker-compose file? (To kubernetes deployments)

example snippet of the docker-compose file:

```
services:
  foo:
    image: foo:1
    hostname: foo
    volumes:
    - ./path/to/file.json:/mount/here
  bee:
    image: bee:1
    hostname: bee
    volumes:
    - /path/to/local/folder:/mount/here
```
(bee has a volume mount of a folder to use as storage, foo has a mount of a json file to use during runtime)

thanks ahead

**Comment by jlevertov** [comment]
After going over the documentation, I don't see an option for doing what I am asking, so I propose a feature:
Adding a label: `kompose.volume.type` using this label a user will be able to specify type of volume he wishes to convert to like: configmap/persistentVolumeClaim/emptyDir etc.

**Comment by hangyan** [comment]
There is already a cmd flags to specify volume types, but it apply to all services. A service label can help this situation.

**Comment by kferrone** [comment]
I like the idea of using the labels for more control. I would suggest using a topology key in the labels to infer what it is for and then omit those labels/annotations from the final output. 

The topology key could be like: `volumes.kubernetes.io` or maybe `io.kompose.volume`
Then these special labels can let kompose know how to set kubernetes specific values

For example:
```yaml
version: "3.7"

services:
  nginx:
    image: nginx
    labels:
      app: nginx
    container_name: app
    hostname: nginx
    volumes:
    - web:/usr/share/nginx/html:Z
    tmpfs:
    - /run
    deploy:
      replicas: 10
    ports: 
    - target: 80
      published: 8080

volumes:
  web:
    name: webvol
    labels: 
      # here we say the generated pvc should have the nfs storageClass
      # after the slash is the key on the corresponding resource
      volumes.kubernetes.io/storageClassName: nfs
```

This way the generated pvc could be:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  # this would be set because of the label in compose on the volume
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
```
