### ISSUE TITLE
Output as many yaml docs

### ISSUE THREAD

**Issue by kferrone** [kubernetes/kompose#1421]
Currently kompose will add all the resources it creates to a kubernetes `List` kind. Is it possible to output to multiple yaml docs instead of a `List`? 

This means instead of 
```yaml
apiVersion: v1
kind: List
metadata: {}
items:
- kind: Deployment
- kind: Service
```
Each resource in the items list would instead be separated by a yaml doc separator:
```yaml
kind: Deployment
---
kind: Service
```
