### ISSUE TITLE
Named Ports

### ISSUE THREAD

**Issue by kferrone** [kubernetes/kompose#1426]
Is there any way to let kompose know what I want to name my ports in the deployment? 

Kompose will just make the name the string value of the port, ie `name: "8080"`

**Comment by kferrone** [comment]
I believe once again a clever label within the compose file can solve this. 

Maybe like this:
```yaml
version: "3.7"

services:
  nginx:
    image: nginx
    labels:
      app: nginx
      # here we say we want port 80 to be named 'web'
      io.kompose.service/ports/80: web
    container_name: app
    hostname: nginx
    ports: 
    - target: 80
      published: 8080
```

Then the port would be named correctly in the service like so:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: nginx
    kompose.cmd: kompose convert --controller=deployment --provider=kubernetes --with-kompose-annotation=true
      --stdout -f /Users/kelly/git/pancakes/kustomize/plugin/mmsg/kompose/example/docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize-v4.3.0
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    # instead of "8080" it is named web
  - name: web
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: nginx
```
