### ISSUE TITLE
HTTP/TCP liveness/readiness probe generation

### ISSUE THREAD

**Issue by sthombare** [kubernetes/kompose#1427]
Is there a way to generate HTTP/TCP readiness/liveness probe as opposed to readiness/liveness command?

**Comment by ichxxx** [comment]
HTTP liveness probe can be generated by specify the labels:
```yaml
labels: 
  kompose.service.healthcheck.liveness.http_get_path: /health/ping
  kompose.service.healthcheck.liveness.http_get_port: 8080
```

But TCP liveness probe and HTTP/TCP readiness probe is not supported yet.

**Comment by ichxxx** [comment]
Can add some labels to support this?
Just like:
```yaml
kompose.service.healthcheck.liveness.tcp_port: 8080
kompose.service.healthcheck.readiness.http_get_path: /ready
kompose.service.healthcheck.readiness.http_get_port: 8080
kompose.service.healthcheck.readiness.tcp_port: 8080
```
