### ISSUE TITLE
Error transforming Kubernetes objects: k.ConfigVolumes failed: stat : no such file or directory

### ISSUE THREAD

**Issue by zestysoft** [kubernetes/kompose#1431]
command:
`kompose -v convert --volumes configMap`

Output:
```
DEBU Checking validation of provider: kubernetes
DEBU Checking validation of controller:
DEBU Docker Compose version: 3
WARN Service "vpn" won't be created because 'ports' is not specified
DEBU Use configmap volume
FATA Error transforming Kubernetes objects: k.ConfigVolumes failed: stat : no such file or directory
```

System details:

MacOS 11.5.2 (Big Sur) Intel
kubectl v1.21.3
kompose 1.24.0 (HEAD)  (From brew install)

docker-compose.yml contents:
```
version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            # Auth token is stored here
            - pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - pia-shared:/pia-shared
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            # The following env vars are required:
            - LOC=swiss
            - USER=p0000000
            - PASS=xxxxxxxxxxxxxxxx
            # The rest are optional:
            # - LOCAL_NETWORK=192.168.1.0/24
            # - KEEPALIVE=25
            # - VPNDNS=8.8.8.8,8.8.4.4
            # - PORT_FORWARDING=1
            # - WG_USERSPACE=1
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    pia:
    pia-shared:
```

I ran dtruss to trace kompose execution, and I'm seeing a stat64 call being passed an empty path (the first parameter), which might be responsible for producing the error, but I'm not sure why that's executing the way it is -- am I missing a field in the yaml file?:

```
read(0x6, "---\nversion: '3'\nservices:\n    vpn:\n        image: thrnz/docker-wireguard-pia\n        volumes:\n            # Auth token is stored here\n            - pia:/pia\n            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use i", 0x574)               = 1395 0
read(0x6, "ut --privileged, so set it here instead if needed\n            - net.ipv4.conf.all.src_valid_mark=1\n            # May as well disable ipv6. Should be blocked anyway.\n            - net.ipv6.conf.default.disable_ipv6=1\n            - net.ipv6.conf.all.disable_", 0x1)             = 0 0
close(0x6)               = 0 0
mmap(0x0, 0x40000, 0x3, 0x41002, 0xFFFFFFFFFFFFFFFF, 0x0)                = 0x3591000 0
write(0x2, "\033[33mWARN\033[0m Service \"vpn\" won't be created because 'ports' is not specified \n\0", 0x4F)           = 79 0
write(0x2, "\033[37mDEBU\033[0m Use configmap volume                         \n\0", 0x3C)                = 60 0
stat64("\0", 0xC0004A7628, 0x0)          = -1 Err#2
write(0x2, "\033[31mFATA\033[0m Error transforming Kubernetes objects: k.ConfigVolumes failed: stat : no such file or directory \n\0", 0x6F)             = 111 0
kevent(0x3, 0x0, 0x0)            = -1 Err#4
```
