### ISSUE TITLE
convert with multiple docker-compose files fails

### ISSUE THREAD

**Issue by jonathandannenberg** [kubernetes/kompose#1444]
The Conversion of multiple docker-compose files doesnt merge the values properly.
Seems related to #1185

Running with: 
1.24.0 (4a2a0458)

Minimum Example:
docker-compose.yml:
```yaml
version: "3.5"
services:
  foo:
    image: foo
    deploy:
      replicas: 3

  bar:
    image: bar
```

docker-compose.prod.yml:
```yaml
version: "3.5"
services:
  bar:
    deploy:
      replicas: 99
```

Expected Behavior:

`kompose convert -f docker-compose.yml -f docker-compose.prod.yml`
I`d expect foo-deployment.yaml with 3 replicas and bar-deployment.yaml with * 99 replicas*

Actual Behavior:
```bash
cat foo-deployment.yaml | grep replicas
  replicas: 3
cat bar-deployment.yaml | grep replicas
  replicas: 1
```
