### ISSUE TITLE
FATA services.xxxxx Additional property secrets is not allowed

### ISSUE THREAD

**Issue by nodje** [kubernetes/kompose#1445]
I'm facing this error when trying to convert a docker-compose.yml file.

My secrets are used directly under the service, as in:
```
 nextcloud:
    image: nextcloud:22.1.1
    restart: always
    container_name: "nextcloud"
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
    depends_on:
      - postgres
    secrets:
      - nextcloud_admin_password
      - nextcloud_postgres_password
      - postgres_password
```
Isn't this supported or are there specific reason why this doesn't work?
