### ISSUE TITLE
Convert docker-compose YAML with profiles

### ISSUE THREAD

**Issue by eltonfss** [kubernetes/kompose#1448]
When trying to convert a docker-compose YAML file with profile specification I get the following error:

```
➜  podman git:(main) kompose convert -f ../docker-compose.yml
FATA services.<myservice> Additional property profiles is not allowed 
```

Example docker-compose.yml:

```
version: '3'
services:
    
  <myservice>:
    image: <myserviceimage>
    profiles:
      - donotstart

  redis:
    image: redis
    ports:
      - "6379:6379"
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

```
