### ISSUE TITLE
convert with provider openshift creates imagestream.yml with no spec.tags.name since 1.22+

### ISSUE THREAD

**Issue by danedb** [kubernetes/kompose#1457]
From docker-compose.yml
```
version: "3"
services:
  redis:
    container_name: redis
    image: redis
```
issuing command `kompose convert --provider openshift`

with version 1.21 leads to imagestream yml
```
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: redis
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
```
and with version 1.25 leads to imagestream yml
```
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: redis
      generation: null
      importPolicy: {}
      name: ""
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
```
where spec.tags.name is missing witch leads to an broken imagestream in openshift if i try to create the resource in openshift 3.11
