### ISSUE TITLE
Kompose creates pvc but without any PV information anywhere?

### ISSUE THREAD

**Issue by getkub** [kubernetes/kompose#1467]
While converting from various docker compose files (especially which has volumes),  kompose creates `PersistentVolumeClaim` (pvc) without relevant PersistentVolume (pv) information

For instance, see the portion below from **docker-compose**
```
    volumes:
      - /vol/elasticsearch_data:/usr/share/elasticsearch/data
      - /vol/elasticsearch_logs:/usr/share/elasticsearch/logs
```

Kompose creates **k8s deployment** file with below info (and there is pvc for each of them name correctly). But the important information of where it is mounted is lost (eg `/vol/elasticsearch_data` ) and thus the application won't start-up properly
```
...
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-claim0
            - mountPath: /usr/share/elasticsearch/logs
              name: elasticsearch-claim1
      restartPolicy: Always
      volumes:
        - name: elasticsearch-claim0
          persistentVolumeClaim:
            claimName: elasticsearch-claim0
        - name: elasticsearch-claim1
          persistentVolumeClaim:
            claimName: elasticsearch-claim1
```

Ideally kompose should retain that information in a 'xxx-persistentvolume.yaml` or combine it within the pvc.yaml file
