### ISSUE TITLE
FATA runtime Additional property runtime is not allowed

### ISSUE THREAD

**Issue by BrightXiaoHan** [kubernetes/kompose#1469]
This is my docker-compose file
```yml
version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: nginx-translate
    ports:
      - "5002:10000"
    links:
      - yyq_translate_general_ru_zh
      - yyq_translate_general_zh_ru

    networks:
      - "front"
      - "backend"
    volumes:
      - "/home/hanbing/models/nginx.conf:/etc/nginx/nginx.conf:ro"


  yyq_translate_general_ru_zh:
    image: translate_server_py:latest-device_cuda-fairseq_v0.10.1
    runtime: nvidia
    container_name: translate_server_yyq_translate_general_ru_zh
    expose:
      - "80"
    networks:
      - "backend"
    volumes:
      - "/home/hanbing/models/yyq_translate_general_ru_zh:/root/translate_server_py/mount"


  yyq_translate_general_zh_ru:
    image: translate_server_py:latest-device_cuda-fairseq_v0.10.1
    runtime: nvidia
    container_name: translate_server_yyq_translate_general_zh_ru
    expose:
      - "80"
    networks:
      - "backend"
    volumes:
      - "/home/hanbing/models/yyq_translate_general_zh_ru:/root/translate_server_py/mount"

networks:
  front:
    driver: bridge
  backend:
    driver: bridge
```
when I convert it with:
```
kompose convert
```
The error raised
<img width="835" alt="截屏2022-01-03 下午12 13 51" src="https://user-images.githubusercontent.com/25839309/147899438-9d403ec9-4085-4ad2-8cc7-87d3d62dac17.png">
