### ISSUE TITLE
Support docker build arguments for Openshift provider

### ISSUE THREAD

**Issue by uroshcheh** [kubernetes/kompose#1479]
Build arguments are not correctly passed from docker-compose to Openshift BuildConfig.

Example docker-compose-yml:

```
version: '3.5'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
      args:
        IMAGE_TAG: 0.9

...
```

Example Dockerfile:

```
ARG IMAGE_TAG
FROM jwilder/nginx-proxy:${IMAGE_TAG:-latest}
```

BuildConfig output:

```
kind: BuildConfig

...

spec:
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: IMAGE_TAG
          value: 0.9
      dockerfilePath: Dockerfile.proxy

...
```

Instead of defining build arguments through `spec.strategy.dockerStrategy.buildArgs`, environmental variables `spec.strategy.dockerStrategy.env` are defined instead, which are not properly passed on to the arguments defined in the Dockerfile.
