### ISSUE TITLE
Wrong "image" value output when context is set

### ISSUE THREAD

**Issue by janusheide** [kubernetes/kompose#1480]
Minimal example
```

|...
|-docker-compose.yaml
|-bar/Containerfile
|--
```

docker-compose.yaml:
```
version: "3.8"
services:

  foo:
    build:
      context:  bar/
      dockerfile: Containerfile
```

Output:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: foo
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: foo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: foo
    spec:
      containers:
        - image: foo
          name: foo
          resources: {}
      restartPolicy: Always
status: {}
```

image should be "bar", not "foo"
