### ISSUE TITLE
Cannot convert docker-compose for long syntax into kubernetes file.

### ISSUE THREAD

**Issue by ChitraRJ** [kubernetes/kompose#1481]
When I use this below docker-compose file for converting into kubernetes file.

version: "3"

services:

  redis-master:
    image: k8s.gcr.io/redis:e2e 
    ports:
    - target: 6379
      published: 6379

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    ports:
    - target: 6379
      published: 6379
    environment:
      - GET_HOSTS_FROM=dns

  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
    - target: 80
      published: 80
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer

This is the error that it produces.

FATA services.frontend.ports.0 must be a string or number

Does it only support short syntax for conversion ?

**Comment by sergeyshevch** [comment]
@ChitraRJ Please note that long port syntax was added only in docker-compose v3.2
So you need to specify version to 3.2 or larger. Then all will works correctly

https://docs.docker.com/compose/compose-file/compose-file-v3/

Example:

```
version: "3.2"

services:

  redis-master:
    image: k8s.gcr.io/redis:e2e
    ports:
      - target: 6379
        published: 6379

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    ports:
      - target: 6379
        published: 6379
    environment:
      - GET_HOSTS_FROM=dns

  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - target: 80
        published: 80
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer
```

@cdrage I guess we can close it then
