### ISSUE TITLE
can not convert `_` of `Network` to `-`

### ISSUE THREAD

**Issue by zaunist** [kubernetes/kompose#1487]
When I was use `kompose convert -f docker-compose.yaml -c` to convert compose file to chart. My compose file `Network` contains `_` like `test_network`, and `kompose` just convert to `test_network` service. But `_` is invalid character in kubernetes service.

May be we should make it more intelligent, a simple way to do this is to convert `_` to `-`.

screenshoot:

![image](https://user-images.githubusercontent.com/38528079/158095567-30acaa4d-6373-48ea-8337-7f06f66a6b74.png)

### If this is necessary, I am happy to do this part of the coding.

**Comment by sergeyshevch** [comment]
Reproduced. 
I can reproduce this issue with compose v3. v1 and v2 correctly handle this case and use normalizeNetworkNames function. v3 don't

example compose file 

```
version: "3"

services:

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    ports:
      - "6379"
    environment:
      - GET_HOSTS_FROM=dns

  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
    networks:
      - test_network
    labels:
      kompose.service.type: LoadBalancer

networks:
  test_network:
    driver: bridge
```
