### ISSUE TITLE
strings containing env vars are not converted and fail

### ISSUE THREAD

**Issue by toxeus** [kubernetes/kompose#1497]
Here's a (contrived for simplicity) `docker-compose.yml` which works properly using `docker-compose` but fails on Kubernetes after converting it with Kompose:
```yaml
version: '3.5'

services:
    myservice:
        image: alpine
        environment:
            PROTOCOL: 'https'
            DOMAIN: 'google.com'
        command:
            [
                'curl',
                '$PROTOCOL://$DOMAIN/',
            ]
```

When the command argument is manually adjusted to `'$(PROTOCOL)://$(DOMAIN)/'` then it works as expected on Kubernetes.

I would expect that Kompose should be able to handle such a case.
