### ISSUE TITLE
Add support to new depends_on scheme and yaml anchors

### ISSUE THREAD

**Issue by ngnix** [kubernetes/kompose#1500]
Hello kompose team!

I use kompose as part of skaffold local builds. 

We have some docker-compose files with new ( compose v3 file references ) syntax, for example:

```yml
---
version: '3'

x-container: &container
  restart: always
  logging:
    options:
      max-size: '200k'
      max-file: '10'

services:
  example_service:
    <<: *container
    image: example_service_image
    env_file:
      - app.env
    expose:
      - 3000
    depends_on:
       openssl-init:
        condition: service_completed_successfully
    healthcheck:
      test: >-
        wget -q --no-check-certificate -O /dev/null http://127.0.0.1:$${PORT:-3000}/health-check
    volumes:
      - init_certs:/certs

  openssl-init:
    <<: *container
    image: example_init_image
    restart: 'no'
    environment:
      HOST: $VIRTUAL_HOST
    volumes:
      - init_certs:/tmp

volumes:
  init_certs:
```

You can see two new sections:

- YAML anchors into docker-compose
- new depends_on conditionals, service_completed_successfully wait for init container have status exit 0

Now if I try to convert this docker-compose.yml file into k8s manifest i have error:

- case one : depends_on, see [docs](https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on) 
```bash
$ kompose -f docker-compose.yml convert 
FATA services.nuxt.depends_on must be a list  
```
I think in this case container `openssl-init` must converted to [k8s init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) , because this container generate certificates for container `example_service`.

- case two : YAML anchors, see [docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields) 
```bash
$ kompose -f docker-compose.yml convert 
FATA (root) Additional property x-container is not allowed
```

Can you add support this features to kompose?

Thanks!
