### ISSUE TITLE
[suggestion] Alpha-numeric service names

### ISSUE THREAD

**Issue by strowi** [kubernetes/kompose#1501]
Hi,

i am currently migrating a couple of docker-compose services to kubernetes. Now i noticed all resulting services are named "$port", which in turn seems to conflict with ingress-naming polices.

For example: 

```version: "3.8"
services:
  emqx:
....
    image: emqx/emqx:4.2.7
    ports:
      - "18083"
```
results in in a service named "18083". Which is not usable as ingress destination:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: emqx
    annotations:
        kubernetes.io/ingress.class: haproxy
spec:
    rules:
      - host: xyz
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "18083"
                port:
                  number: 18083
```

> The Ingress "emqx" is invalid: spec.rules[0].http.paths[0].backend.service.name: Invalid value: "18083": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')

For ease of use, would be possible to just prepend a letter to the service-names (like "p18083")?

Otherwise kompose has taken a lot of work away from me.;)

best regards,
strowi
