### ISSUE TITLE
Add loadBalancerIP to assign static IP to LoadBalancer

### ISSUE THREAD

**Issue by emouawad** [kubernetes/kompose#1502]
Services of type LoadBalancer support loadBalancerIP: "YOUR.IP.ADDRESS.HERE"

Not sure if it's possible to assign load balancer static ip via docker-compose networks or this still needs a conversion.
Basically what i need to do is assign a static ip to the load balancer as opposed to the auto assigned service external-ip

kompose.service.type: LoadBalancer

```yml
apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "YOUR.IP.ADDRESS.HERE"
```
