### ISSUE TITLE
[Question] FATA services.django Additional property platform is not allowed 

### ISSUE THREAD

**Issue by scheung38** [kubernetes/kompose#1503]
Below is example of my production.yml for Django, when

kompose --file production.yml convert

I get:

FATA services.django Additional property platform is not allowed 

Why is that please?

.tool-versions
python 3.10.4
kompose 1.26.0

--------------------------------------------------------------------

```
version: '3'

volumes:
  production_mongodb_data:
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: XXXacr.azurecr.io/XXXX_production_django:v1.0.0
    platform: linux/x86_64.      <-----------??????
    depends_on:
      - mongo
    volumes:
      - .:/app:z
      - $HOME/Desktop/XXX_data/_XXX_Data_samples/XXX_MAIN_FILE:/uploaddata  
    
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mongodb
    ports:
      - "8000:8000"
      - "3000:3000"      
    command: /start
    stdin_open: true
    tty: true

  mongo:
    image: mongo:5.0.6
    container_name: "mongo"
    restart: always
    env_file:
      - ./.envs/.production/.mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=XXXXX
      - MONGO_INITDB_ROOT_PASSWORD=XXXXX
      - MONGO_INITDB_DATABASE= XXXX_mongo 
      - MONGO_INITDB_USERNAME=XXXXX
      - MONGO_INITDB_PASSWORD=XXXXX 
    volumes:
      - production_mongodb_data:/data/db
    ports:
      - 27017:27017

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: XXXX_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

```
