### ISSUE TITLE
Multiple volumes

### ISSUE THREAD

**Issue by ubearline** [kubernetes/kompose#1509]
I have a container that needs both a configmap and a regular volume. Is there a way to set the type for the volume separately. 

# example

```
version: "3.4"
services:
  postgres:
    image: postgres:12.8
    labels:
      kompose.volume.type: configMap # This will make all volumes configmap
    ports:
    - 5432:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data   # PVC
    - ./config/postgres_init:/docker-entrypoint-initdb.d # configMap
```
