### ISSUE TITLE
Bug or feature: server can't find hostname: SERVFAIL

### ISSUE THREAD

**Issue by mikahe** [kubernetes/kompose#1511]
I'm new to Kubernetes and Kompose, so please take this report with a grain of salt. I noticed this issue with docker-compose hostname resolution after converting a real world docker-compose.yml but reproduced the issue in this repro example.

docker-compose.yml:
```
version: '3.8'

services:
  nginx-service:
    image: nginx
    container_name: nginx-container_name
    hostname: nginx-hostname
    ports:
     - "8090:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

  dns-utils:
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command: "sleep 3000"
```

`kubectl -n kompose get pods`

> 
> NAME                             READY   STATUS    RESTARTS   AGE
> dns-utils-795ff99676-scs5w       1/1     Running   0          2m7s
> nginx-service-75998c454b-z7rw6   1/1     Running   0          2m7s

`kubectl -n kompose exec -i -t dns-utils-795ff99676-scs5w -- nslookup nginx-hostname`

> 
> Server:		10.96.0.10
> Address:	10.96.0.10#53
> 
> ** server can't find nginx-hostname: SERVFAIL

`kubectl -n kompose exec -i -t dns-utils-795ff99676-scs5w -- nslookup nginx-service`

> Server:		10.96.0.10
> Address:	10.96.0.10#53
> 
> Name:	nginx-service.kompose.svc.cluster.local
> Address: 10.103.89.1
