### ISSUE TITLE
Error while adding a new ingress

### ISSUE THREAD

**Issue by AhmedGrati** [kubernetes/kompose#1527]
# Description
Generating a new ingress using Kompose faced some issues. In fact, the generated ingress does not have a `spec.ingressClassName` in its spec file, which resulted in errors, especially for new Kubernetes versions.
# Steps to reproduce
1- Create a `docker-compose.yaml` file:
```yaml
version: "3.8"

services:
  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.expose: lb
```
2- execute the following command: `kompose convert -f docker-compose.yaml`
3- inspect the generated ingress file. It be like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.service.expose: lb
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  rules:
    - host: lb
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
```
