### ISSUE TITLE
FATA xxx.depends_on must be a list

### ISSUE THREAD

**Issue by MikeRohsoft** [kubernetes/kompose#1533]
```yml
version: '3.7'
services:  
  mysql:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - 3306
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="${MYSQL_DB_PASSWORD}" --silent']
      interval: 3s
      retries: 5
      start_period: 30s      
      
  nginx:
    image: nginx
    depends_on:
      mysql:
        condition: service_healthy
```
