### ISSUE TITLE
Kompose fails if docker-compose.yaml uses extension fields

### ISSUE THREAD

**Issue by larsks** [kubernetes/kompose#1548]
Many docker compose configurations use [extension fields](https://docs.docker.com/compose/compose-file/#extension) to hold common configuration elements, which are applied to service definitions via yaml anchors. E.g:

```yaml
x-common:
  &common
  image: myrepo/myimage
  volumes:
    app_data: /data

services:
  example-service:
    <<: *common
    command: webserver
    ports:
      - 8080:8080
```

Kompose fails to process these files with the following error:

```
FATA (root) Additional property x-common is not allowed
```

Kompose should ignore `x-` extension fields in the compose file, and it should be using a YAML parser with proper support for anchors and references.

**Comment by AhmedGrati** [comment]
@larsks what is the Kompose version that you are using?

**Comment by larsks** [comment]
This happens with Kompose `1.27.0 (b0ed6a2c9)`.

It looks like the behavior is perhaps overly-strict parsing of the `version:` key. Given:

```
version: "3"

x-common:
  ...
```

While `docker-compose` and `docker compose` are both able to parse that without complaint, `kompose` complains unless the `version` is updated to be `3.4` or later.

**Comment by cdrage** [comment]
> 

Hey @larsks give me about 12 hours and you'll have a new Kompose release to test this out against and see if the issue has been resolved :)

**Comment by cdrage** [comment]
@AhmedGrati I don't think this has been resolved yet

**Comment by github-daniel-stoian** [comment]
It's working  with version 3.7:

version: "3.7"

x-common-labels: &common-labels
  kompose.image-pull-secret: "ecr"
  kompose.image-pull-policy: "Always"
  kompose.service.type: "nodeport"

**Comment by larsks** [comment]
@github-daniel-stoian I think you may have misunderstood the problem report. Take a look at [this comment](https://github.com/kubernetes/kompose/issues/1548#issuecomment-1399658766) for details.

**Comment by AhmedGrati** [comment]
@larsks I ran the following example, with Kompose version `1.28.0`, and it works fine:
```yaml
x-common:
  &common
  image: myrepo/myimage
  volumes:
  - app_data:/data

services:
  example-service:
    <<: *common
    command: webserver
    ports:
      - 8080:8080
volumes:
  app_data:
```
Can you confirm that?
