### ISSUE TITLE
Dependabot integration

### ISSUE THREAD

**Issue by Lctrs** [kubernetes/kompose#1551]
IMHO, it would be a good thing to integrate Dependabot (or a similar tool) to get compose-go updates ASAP. But I don't know how this integrates with the CLA workflow. Any tips ?

**Comment by cdrage** [comment]
I've gone ahead and updating the repo to receive dependabot alerts as well as security alerts, but not version alerts (yet). Just figuring out what we need to do to the CI to get that enabled.

**Comment by Lctrs** [comment]
To get automatic PR to update dependencies, you just have to create a `.github/dependabot.yaml` in the repo. The config below would be a good start : 
```yaml
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - commit-message:
      include: "scope"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"

  - commit-message:
      include: "scope"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
```
