### ISSUE TITLE
Docs: Labels should be elaborated more

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1576]
The page here: https://kompose.io/user-guide/#labels

The label is confusing to read and process.

We should have a section (header 3 / `###`) for EACH label explaining it with an example.

**Comment by cdrage** [comment]
`kompose.service.group` is a pretty important label and unfortunatley not much documentation on that either.

We'll have to showcase and document each label and what it does (and the corresponding kubernetes yaml that it outputs too)

**Comment by sosan** [comment]
`examples, opinions?`


### kompose.service.type
`kompose.service.type` label defines the type of service to be created. There are several types to choose: `nodeport` / `clusterip` / `loadbalancer` / `headless`

In this example `kompose.service.type` label is set to nodeport. 

```yaml
services:
  nginx:
    image: nginx
    build: 
      context: ./foobar
      dockerfile: foobar
    cap_add:
      - ALL
    container_name: foobar
    ports:
      - 8080:80
    labels:
      kompose.service.type: nodeport
```

Converted docker compose file exposes the service on a static port on each worker node.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: nginx
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx
          name: foobar
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - ALL
      restartPolicy: Always
```

### kompose.service.nodeport.port
`kompose.service.nodeport.port` label defines the port value when service type is `nodeport`, this label should only be set when the service only contains 1 port. Usually kubernetes define a port range for node port values, kompose will not validate this.

```yaml
services:
  nginx:
    image: nginx
    ports:
      - 9090:80
    labels:
      kompose.service.nodeport.port: 9090
      kompose.service.type: nodeport
```

converted:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "9090"
      nodePort: 9090
      port: 9090
      targetPort: 80
  selector:
    io.kompose.service: nginx
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 9090
              protocol: TCP
      restartPolicy: Always
```

### kompose.service.expose 
`kompose.service.expose` label defines if the service needs to be made accessible from outside the cluster or not. If the value is set to "true", the provider sets the endpoint automatically, and for any other value, the value is set as the hostname. If multiple ports are defined in a service, the first one is chosen to be the exposed.

For the Kubernetes provider, an ingress resource is created, and it is assumed that an ingress controller has already been configured. If the value is set to a comma-separated list, multiple hostnames are supported. Hostname with the path is also supported.

For the OpenShift provider, a route is created.

In this example `kompose.service.expose` label is set to endpoints `counter.example.com,foobar.example.com`

Docker compose file:

```yaml
version: "2"
services:
  web:
    image: tuna/docker-counter23
    ports:
     - "5000:5000"
    links:
     - redis
    labels:
      kompose.service.expose: "counter.example.com,foobar.example.com"
  redis:
    image: redis:3.0
    ports:
     - "6379"
```

converted to kubernetes deployment, service, ingress:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:3.0
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: tuna/docker-counter23
          name: web
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  rules:
    - host: counter.example.com
      http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 5000
            path: /
            pathType: Prefix
    - host: foobar.example.com
      http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 5000
            path: /
            pathType: Prefix
```
