### ISSUE TITLE
Add support `subPath` (Some containers complain about mounting volume at root path.)

### ISSUE THREAD

**Issue by WalkerWalker** [kubernetes/kompose#1603]
### Expected Behavior

Be able to convert a simple docker-compose.yaml file with only one service postgres

### Actual Behavior

The generated files cannot be used directly because the volume is not empty at root (/) and the error messages from postgres are as follows

```
initdb: directory "/var/lib/postgresql/data" exists but is not empty It contains a lost+found directory, 
perhaps due to it being a mount point. Using a mount point directly as the data directory is not recommended. 
Create a subdirectory under the mount point.
```

Therefore, as suggested from the error message,  I can simply configure the subpath in the DeploymentConfig
```
volumeMounts:
- mountPath: /var/lib/postgresql/data
  name: postgres-data
  subPath: postgres  # this line is manually added
```

I can confirm that it works after adding the [subPath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) 

### Steps To Reproduce

```
kompose convert -f docker-compose.yaml --provider openshift
```

### Kompose Version

```Text
1.28.0 (c4137012e)
```

### Docker-Compose file

```YAML
version: '3.8'
volumes:
  postgres-data:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dumb_postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: dumb_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
```

### Anything else?

I am aware that there are different ways to modify the docker-compose file or to modify the generated file to make it work.  Like mount a parent directory, or configure PGDATA env.  This issue is more of a request for the feature of defining `subPath`, maybe as a kompose lable and so that it can be generated as indicated by the label?
