### ISSUE TITLE
Support Docker Compose 3.9

### ISSUE THREAD

**Issue by MarkCupitt** [kubernetes/kompose#1617]
### What would you like to be added?

Support for Docker compose 3.9

```
version: "3.9"

services:
  db:
    profiles: ["dev", "prod", "test"]
    image: postgres:13
    container_name: mathesar_db
    environment:
```

```
$ kompose convert
FATA version 3.9 of Docker Compose is not supported. Please use version 1, 2 or 3 
```

### Why is this needed?

Have files to convert
