### ISSUE TITLE
[BUG] environment variable interpolation not used for special labels

### ISSUE THREAD

**Issue by antdking** [kubernetes/kompose#1634]
### Expected Behavior

attempting to use environment variables to control different things, such as whether to try pulling the image (useful for local development when you're injecting images into the cache).

ie:
```yaml
labels:
  kompose.image-pull-policy: ${IMAGE_PULL_POLICY:-IfNotPresent}
```

Expecting the manifests to be rendered with whatever I set `IMAGE_PULL_POLICY` to.
This works with v1.27.

### Actual Behavior
errors out:

```
FATA Error transforming Kubernetes objects: k.UpdateController failed: updateTemplate failed: Unknown image-pull-policy ${IMAGE_PULL_POLICY} for service foo 
```

### Kompose Version

```Text
1.28.0 (c4137012e)
```

### Docker-Compose file

```YAML
services:
  foo:
    labels:
      kompose.image-pull-policy: "${IMAGE_PULL_POLICY:-IfNotPresent}"
    build: .
```

### Anything else?

current workaround is to pre-process with docker compose:

```sh
kompose convert -f <(IMAGE_PULL_POLICY=Never docker compose config)
```
