### ISSUE TITLE
$ in command is to aggressively replaced with $()

### ISSUE THREAD

**Issue by mihaichitic** [kubernetes/kompose#1636]
### Expected Behavior

it should translate to:
```
spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |
              echo '$$variable'
              echo $${VAR:+--flag "$$VAR"}
          env:
            - name: VAR
              value: flagValue
            - name: variable
              value: 'should not be interpolated'
          image: alpine
          name: app
```
which results in kubernetes the following output:
```
$variable
--flag flagValue
```

### Actual Behavior

it translates to
```
spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |
              echo '$()$(variable)'
              echo $()$(){VAR:+--flag "$()$(VAR)"}
          env:
            - name: VAR
              value: flagValue
            - name: variable
              value: 'should not be interpolated'
          image: alpine
          name: app
```

which in kubernetes will result the following output
```
$()should not be interpolated
{VAR:+--flag flagValue}
```

### Kompose Version

```Text
1.28
```

### Docker-Compose file

```YAML
services:
  app:
    image: alpine
    command:
        - /bin/sh
        - -c
        - |
          echo '$$variable'
          echo $${VAR:+--flag "$$VAR"}
    environment:
        variable: 'should not be interpolated'
        VAR: 'flagValue'
```

**Comment by SBD580** [comment]
Also, seems like underscores are not treated property: `$A_B` => `$(A)_B`

**Comment by AhmedGrati** [comment]
@sfdumi I can assign it to you if you want to open a PR for this issue.

**Comment by sfdumi** [comment]
Sure.

**Comment by fresh2dev** [comment]
The `docker-compose` CLI offers this flag:

```
--no-interpolate          Don't interpolate environment variables
```

The user could work around this issue if `kompose` offered the same.

I was actually hoping to run my compose.yaml through `kompose convert`, then rewrite this output:

```
spec:
  containers:
    - env:
        - name: HELLO
          value: $WORLD
```

Into this:

```spec:
containers:
  - env:
      - name: HELLO
        valueFrom:
          secretKeyRef:
            name: my-app-secret-env
            key: WORLD
```

But I can't find a way to disable variable interpolation nor escape environment variables.
