### ISSUE TITLE
[BUG] Missing `imagePullSecret` when converting to Helm with many containers in one Pod

### ISSUE THREAD

**Issue by bl-sarus** [kubernetes/kompose#1645]
### Expected Behavior

When I use the CLI argument `--service-group-mode=label`, I expect the `imagePullSecret` property to be added to the generated files `chart/templates/*-deployment.yaml` or `chart/templates/*-statefulset.yaml`:
```
      imagePullSecrets:
        - name: mysecret
```

### Actual Behavior

It is missing, resulting in errors when the Helm install requires pulling images from a private registry.

### Steps To Reproduce

Using the attached docker-compose, I get the following outcomes:
- `kompose convert --service-group-mode=label -c -f docker-compose.yaml`: missing parameter
- `kompose convert --service-group-mode=label --controller statefulset -c -f docker-compose.yaml`: missing parameter
- `kompose convert -c -f docker-compose.yaml`: `imagePullSecrets` is present in deploy files
- `kompose convert --controller statefulset -c -f docker-compose.yaml`: `imagePullSecrets` is present in statefulset files

### Kompose Version

```Text
1.28.0 (c4137012e)
```

### Docker-Compose file

```YAML
version: '3'
services:
  container-1:
    image: busybox
    command:
      - sh
      - -c
      - 'while true; echo "container-1 running"; sleep 10; done'
    labels:
      kompose.image-pull-secret: mysecret
      kompose.service.group: mygroup
  container-2:
    image: busybox
    command:
      - sh
      - -c
      - 'while true; echo "container-2 running"; sleep 10; done'
    labels:
      kompose.image-pull-secret: mysecret
      kompose.service.group: mygroup
```
```


### Anything else?

_No response_
