### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by eliassal** [kubernetes/kompose#1652]
### Expected Behavior

Deployments to run using Kompose in yaml descriptor files

### Actual Behavior

When issuing 
`Kubectl create -f cart-deployment.yaml `
with following contents

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: cart
  name: cart
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cart
    spec:
      containers:
      - image: linuxacademycontent/rs-cart:latest
        name: cart
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
status: {}
```

When I run

 kubectl -n robot-shop create -f cart-deployment.yaml

I get the following stopping error:

The Deployment "cart" is invalid:
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"io.kompose.service":"cart"}: `selector` does not match template `labels`

What is missing

### Steps To Reproduce

I cloned the git repo at 
 https://github.com/linuxacademy/robot-shop.git

In K8s/descriptors/ directory I updated the kompose version in the file cart-deployment.yaml

ran the kubectl creat command as indicated earlier

### Kompose Version

```Text
1.28.0 (c4137012e) on ubuntu 22.04
```

### Docker-Compose file

```YAML
version: '3'
services:
  mongodb:
    build:
      context: mongo
    image: ${REPO}/rs-mongodb:${TAG}
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis:
    image: redis:4.0.6
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  catalogue:
    build:
      context: catalogue
    image: ${REPO}/rs-catalogue:${TAG}
    depends_on:
      - mongodb
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  user:
    build:
      context: user
    image: ${REPO}/rs-user:${TAG}
    depends_on:
      - mongodb
      - redis
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  cart:
    build:
      context: cart
    image: ${REPO}/rs-cart:${TAG}
    depends_on:
      - redis
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  mysql:
    build:
      context: mysql
    image: ${REPO}/rs-mysql-db:${TAG}
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  shipping:
    build:
      context: shipping
    image: ${REPO}/rs-shipping:${TAG}
    depends_on:
      - mysql
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  ratings:
    build:
      context: ratings
    image: ${REPO}/rs-ratings:${TAG}
    networks:
      - robot-shop
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  payment:
    build:
      context: payment
    image: ${REPO}/rs-payment:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  dispatch:
    build:
      context: dispatch
    image: ${REPO}/rs-dispatch:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  web:
    build:
      context: web
    image: ${REPO}/rs-web:${TAG}
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # Uncomment to enable Instana EUM
    # environment:
      # INSTANA_EUM_KEY: <your eum key here>

networks:
  robot-shop:
```

### Anything else?

I replaced io.kompose.service in the labels by app and added a selector, kubectl creation goes through but deployments always stuck in "Non-Ready state" as well as the Pods in "ContainerCreationState"
