### ISSUE TITLE
[BUG] kompose.service.expose label converts Helm variables to lowercase on translation into ingress host

### ISSUE THREAD

**Issue by init-penguin** [kubernetes/kompose#1663]
### Expected Behavior

Having set
```
...
    labels:
      kompose.service.expose: "{{ .Release.Name }}.{{ .Release.Namespace }}.tld"
      ...
```
`kompose convert -c` should generate following ingress.yaml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  rules:
    - host: '{{ .Release.Name }}.{{ .Release.Namespace }}.tld'
    ...
```
Ingress annotation, however, translates perfectly fine.

### Actual Behavior

Instead generated ingress.yaml looks like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  rules:
    - host: '{{ .release.name }}.{{ .release.namespace }}.tld'
    ...
```
and thus does not substitute corresponding Helm variables

### Kompose Version

```Text
1.2{8,9}.0
```

### Anything else?

If this is intended behaviour and not a bug, i'd suspect a fair warning in Docs like "Do not attempt to use Helm variables inside labels / this particular label"

Thanks in advance!
