### ISSUE TITLE
[BUG] read_only value in docker-compose not respected

### ISSUE THREAD

**Issue by szaimen** [kubernetes/kompose#1668]
### Expected Behavior

`read_only: true` when running `kompose -c -f compose.yaml` should also be found in the kubernetes config

### Actual Behavior

It is not kept.

### Steps To Reproduce

1. have this compose.yaml:
```
services:
  test:
    image: alpine
    read_only: true
```
2. run kompose -c -f compose.yaml

### Kompose Version

```Text
v1.29
```

### Docker-Compose file

```YAML
services:
  test:
    image: alpine
    read_only: true
```
