### ISSUE TITLE
[BUG] pod env_file does not create configmaps

### ISSUE THREAD

**Issue by realgam3** [kubernetes/kompose#1683]
### Expected Behavior

docker-compose:
```yaml
version: "3"

services:
  pod:
    image: busybox
    env_file:
      - "envs/pod.env"
    restart: "no"

  deployment:
    image: busybox
    env_file:
      - "envs/deployment.env"
    restart: "always"
```
* Should create 2 **ConfigMaps**: envs-deployment-env & envs-pod-env. 

### Actual Behavior

Creates only 1 ConfigMap: envs-deployment-env 
* in Windows it fails to create any ConfigMap.
  **reason**:  service.EnvFile is not relative and it cause issues with some functions.

### Steps To Reproduce

2. Create envs directory
3. Create 2 files envs/deployment.env and envs/pod.env with the contents of `TEST=TEST`
4. Run command: `kompose convert`

### Kompose Version

```Text
1.30.0 
Branch: main
Commit: 17fbe3b4632cca0f61a7fda5f3b91034cdf5c5e4
```

### Docker-Compose file

```YAML
version: "3"

services:
  pod:
    image: busybox
    env_file:
      - "envs/pod.env"
    restart: "no"

  deployment:
    image: busybox
    env_file:
      - "envs/deployment.env"
    restart: "always"
```
