### ISSUE TITLE
[BUG] kompose convert ignoring services when profiles is set

### ISSUE THREAD

**Issue by axel7083** [kubernetes/kompose#1708]
### Expected Behavior

We would expect a warning, or any kind of information when dealing with docker-compose file with _profiled_ services.

And for example supporting an option like `--profile`

### Actual Behavior

Nothing is output when using it. If we use `-o output.yaml`, the `output.yaml` file will be empty

### Steps To Reproduce

`kompose.exe convert -f .\docker-compose.yaml -o output.yaml`

### Kompose Version

```Text
latest
```

### Docker-Compose file

```YAML
version: "3.8"

services:
  redis:
    image: redis
    restart: always
    profiles: ["frontend-dev", "backend-dev", "ci"]
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 2s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
```
