### ISSUE TITLE
[BUG] Unable to process YAML 1.2 files

### ISSUE THREAD

**Issue by mdvthu** [kubernetes/kompose#1711]
### Expected Behavior

Should be able to process YAML 1.2 files

### Actual Behavior

docker-compose.yaml files with `%YAML 1.2` in the header aren't currently supported, producing the error output:

`FATA Unable to load files: parsing /home/username/services/example-service/docker-compose.yaml: yaml: found incompatible YAML document`

### Steps To Reproduce

docker-compose.yaml file with the following first line:

`%YAML 1.2`

Run:

`kompose convert`

Removing `%YAML 1.2` or changing to `%YAML 1.1` and it works

### Kompose Version

```Text
1.30.0 (HEAD)
```

### Docker-Compose file

```YAML
%YAML 1.2
---
# SPDX-FileCopyrightText: 2023 Mark Thurston
# SPDX-License-Identifier: Apache-2.0
version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller:7.5.174-ls206
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024
    volumes:
      - '$HOME/.local/share/unifi/config:/config'
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped
    labels:
      kompose.service.type: LoadBalancer
```
