### ISSUE TITLE
[BUG] escape double curly braces when converting to configmap

### ISSUE THREAD

**Issue by s33kers** [kubernetes/kompose#1751]
### Expected Behavior

Having double curly braces in volume files should create valid Helm chart at the end 

e.g.  `{{` replaces with `{{ "{{" }}` https://github.com/helm/helm/issues/2798#issuecomment-326454957

### Actual Behavior

Having double curly braces in volume files creates invalid Helm chart which cannot be used straight-forward after kompose converting. or generic practice should be described how to workaround in such case. 

### Steps To Reproduce

1. create `docker-compose.yaml` with
```
version: '3'
services:
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - --global-response-templating
```
2. create `./wiremock/test.json` with
```
apiVersion: v1
data:
  test.json: |
    {
        "request": {
            "urlPathPattern": "/test/.*",
            "method": "GET"
        },
        "response": {
            "status": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "transformers": ["response-template"],
            "jsonBody": {
                "test": {
                    "id": "{{reqestu.path.[1]}}"
                }
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wiremock
  name: wiremock-cm0
```
3. run `kompose convert --file docker-compose.yaml --chart --volumes configMap`
4. run `helm template "test" ./docker-compose` which returns 
```
Error: parse error at (docker-compose/templates/wiremock-cm0-configmap.yaml:17): function "request" not defined
```
5. open `./docker-compose/templates/wiremock-cm0-configmap.yaml`
6. double curly brackets are not escaped and it breaks
```
apiVersion: v1
data:
  test.json: |
    {
        "request": {
            "urlPathPattern": "/test/.*",
            "method": "GET"
        },
        "response": {
            "status": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "transformers": ["response-template"],
            "jsonBody": {
                "test": {
                    "id": "{{request.path.[1]}}"
                }
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wiremock
  name: wiremock-cm0
```
7. change `"id": "{{request.path.[1]}}"` to `"id": "{{ "{{" }}request.path.[1]{{ "}}" }}"` 
8. run `helm template "test" ./docker-compose` which returns valid Helm chart

### Kompose Version

```Text
1.31.2 (a92241f79)
```

### Docker-Compose file

```YAML
version: '3'
services:
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - --global-response-templating
```
