### ISSUE TITLE
Remove other useless keys in output

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1758]
### What would you like to be added?

```yaml
▶ cat frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (37a1dc26a)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.1 (37a1dc26a)
      creationTimestamp: null
      labels:
        io.kompose.network/downloads-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: cdrage/frontend
          name: frontend
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
```

### Why is this needed?

There are keys which are useless in the output we should remove such as:

* strategy {}
* resources: {}
* status: {}
