### ISSUE TITLE
What is `io.kompose.network`?

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1759]
### What would you like to be added?

For some reason we get a lot of this output:

```yaml
      labels:
        io.kompose.network/downloads-default: "true"
        io.kompose.service: frontend
```

In a simple example like:

```yaml
services:

  redis-master:
    container_name: redis-master
    image: redis:latest
    ports:
      - "6379"

  redis-replica:
    container_name: redis-replica
    image: redis:latest
    ports:
      - "6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master

  frontend:
    container_name: frontend
    image: cdrage/frontend
    #build: ./frontend
    ports:
      - "8080:8080"
```

Why? Even in our documentation we do not have any information on kompose.network labels.

I think this should be removed as they provide no benefits to k8s deployment.

### Why is this needed?

Unneeded label.
