### ISSUE TITLE
[BUG] Kompose doesn't work with Docker-compose version 3

### ISSUE THREAD

**Issue by DavDeDev** [kubernetes/kompose#1771]
### Expected Behavior

I am follwing the steps here: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/#use-kompose and I am expecting the yaml files to be generated, but they are only generated if I change my docker-compose version to 2.

### Actual Behavior

`FATA (root) Additional property name is not allowed`

### Kompose Version

```Text
1.26.0 (40646f47)
```

### Docker-Compose file

```YAML
version: '3'

name: dewallet-development
services:
  DeWallet-app:
    container_name: development-fullstack
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: dewallet-app-development
    ports:
      - '3001:3000'
```
