### ISSUE TITLE
run-kompose pre-commit hook

### ISSUE THREAD

**Issue by znd4** [kubernetes/kompose#1780]
### What would you like to be added?

Would it be reasonable to add  a.pre-commit-hooks.yaml to the kompose repo? I'd love to write a (probably pretty simple) PR if it seems appropriate.

The goal would be to enable the following `.pre-commit-config.yaml`

```yaml
repos:
  - repo: https://github.com/kubernetes/kompose
    rev: ...
    hooks:
      - id: run-kompose # should this just be kompose?
        args: convert -o k8s/
        # not sure about the regex atm, but hopefully you get the idea
        files: "(docker-compose\.yaml|k8s/*")
```

This can currently be somewhat implemented with `repo: local` and `language: system`, with obvious downsides

```yaml
repos:
  - repo: local
    hooks:
      - id: run-kompose
        language: system
        entry: kompose ...
        files: ...
```

Unfortunately, this requires installing kompose separately, ruling out pre-commit.ci, and adding maintenance overhead to CI pipelines.

### Why is this needed?

The use-case would basically be to continue to use docker-compose.yaml as our development platform, (at least until we can figure out a `skaffold workflow that works for us).

This might be against the philosophy of "moving people away from docker-compose", so I'd understand not wanting to add this.
