### ISSUE TITLE
[BUG] Conflicting name assigned to configmap generated for compose referencing ".env" files

### ISSUE THREAD

**Issue by Pratham1812** [kubernetes/kompose#1793]
### Expected Behavior

Compose files which refer to environment variables from files such as ".env" or ".env.local" in a simple React application should produce a configmap file whose filename follows the appropriate regex rules required by kubernetes.

### Actual Behavior

For compose referencing env_files begining with ".env", the generated file name of configmap does not follow appropriate regex rules, which prevents deployment on minikube or any other platform. 

### Steps To Reproduce

1. For this `docker-compose.yaml`
```bash
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - 27017
  app:
    depends_on:
      - mongodb
    env_file:
      - ./src/app/.env.local
    build: src/
    ports:
      - "3000:3000"
```
2. On running `kompose convert -f docker-compose.yaml`
3.  File name for configmap `< path with '/' replace with '-' >-app--env-configmap.yaml`
4. On minikube run `kubectl apply -f app-deployment.yaml`
5. The deployment is not created
![image](https://github.com/kubernetes/kompose/assets/32198580/7e216b97-2620-42e1-a172-b7f9aea481aa)

### Kompose Version

```Text
1.31.2 (a92241f79)
```

### Docker-Compose file

```YAML
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - 27017
  app:
    depends_on:
      - mongodb
    env_file:
      - ./src/app/.env
    build: src/
    ports:
      - "3000:3000"
```

### Anything else?

The issue seems to be in `kompose/pkg/transformer/kubernetes/k8sutils.go` in the `FormatEnvName` function where the '.' has been replaced with '-' and can be resolved as shown in the below screen shot .

![image](https://github.com/kubernetes/kompose/assets/32198580/c502370a-3587-45e9-a123-9c16e36a9380)

Thanks
