### ISSUE TITLE
[BUG] fail to convert example

### ISSUE THREAD

**Issue by joshuacox** [kubernetes/kompose#1814]
### Expected Behavior

Convert the example file.

### Actual Behavior

kompose convert -f compose.yaml
ERRO Could not parse config for project noworky : Unsupported config option for redis-replica service: 'redis-leader'
Unsupported config option for web service: 'redis-replica'
Unsupported config option for services service: 'web' 
FATA composeObject.Parse() failed, Failed to load compose file: Unsupported config option for redis-replica service: 'redis-leader'
Unsupported config option for web service: 'redis-replica'
Unsupported config option for services service: 'web'

### Steps To Reproduce

1. go install github.com/kubernetes/kompose@latest 
1.  wget https://raw.githubusercontent.com/kubernetes/kompose/main/examples/compose.yaml
1. kompose convert -f compose.yaml
ERRO Could not parse config for project noworky : Unsupported config option for redis-replica service: 'redis-leader'
Unsupported config option for web service: 'redis-replica'
Unsupported config option for services service: 'web' 
FATA composeObject.Parse() failed, Failed to load compose file: Unsupported config option for redis-replica service: 'redis-leader'
Unsupported config option for web service: 'redis-replica'
Unsupported config option for services service: 'web'

### Kompose Version

```Text
kompose version                
1.22.0 (955b78124)
```

### Docker-Compose file

```YAML
cat compose.yaml
services:

  redis-leader:
    container_name: redis-leader
    image: redis:latest
    ports:
      - "6379"

  redis-replica:
    container_name: redis-replica
    image: redis:latest
    ports:
      - "6379"
    command: redis-server --replicaof redis-leader 6379

  web:
    container_name: web
    image: quay.io/kompose/web
    ports:
      - "8080:8080"
```

### Anything else?

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -a
Linux saruman 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

go version
go version go1.19.8 linux/amd64
