### ISSUE TITLE
[BUG] Creating ConfigMaps from volume mounts in windows is unsuccessful when the working directory is specified as an absolute path.

### ISSUE THREAD

**Issue by realgam3** [kubernetes/kompose#1829]
### Expected Behavior

The compose workdir generated by an internal function [getComposeFileDir](https://github.com/kubernetes/kompose/blob/d872afb3773e74de1cb8df6f3d92236d54a9a0da/pkg/loader/compose/utils.go#L138) instead of the improved function [transformer.GetComposeFileDir](https://github.com/kubernetes/kompose/blob/d872afb3773e74de1cb8df6f3d92236d54a9a0da/pkg/transformer/utils.go#L338)

### Actual Behavior

the workdir will be generated with transformer.getComposeFileDir that uses filepath functions instead of searching for the index of "/". 

### Steps To Reproduce

1. Create file in `./tls/a.key` along to the docker-compose.yml file
2. Run `-f C:\another-path\docker-compose.yml convert --stdout --with-kompose-annotation=false` command from another path
3.  Check if ConfigMap created

### Kompose Version

```Text
1.32.0
```

### Docker-Compose file

```YAML
version: "3"

services:
  web:
    image: nginx
    volumes:
      - ./tls/a.key:/etc/test-a-key.key
    labels:
      kompose.volume.type: configMap
```
