### ISSUE TITLE
[BUG] Environment variables containing `status:` are removed

### ISSUE THREAD

**Issue by jaapenstaart** [kubernetes/kompose#1853]
### Expected Behavior

I want to use `status:xxx` as a value of one of envirnoment variables

### Actual Behavior

It removes `status:` and the subsequent lines in the generated `app-deployment.yaml`

### Steps To Reproduce

Run `kompose convert` with v1.32.0 with attached dock-compose file

### Kompose Version

```Text
1.32.0
```

### Docker-Compose file

```YAML
services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    environment:
      TOPICS: foo:1,status:2,bar:3
      OTHER_ENV: example
```

### Anything else?

Bug seems to be introduced in this PR: https://github.com/kubernetes/kompose/pull/1746
