### ISSUE TITLE
[BUG] mapping format of services[].env_file is not supported

### ISSUE THREAD

**Issue by jancespivo** [kubernetes/kompose#1855]
### Expected Behavior

Mapping format as it is described https://docs.docker.com/compose/compose-file/05-services/#env_file should be supported.

```
env_file:
  - path: ./default.env
    required: true # default
  - path: ./override.env
    required: false
```

### Actual Behavior

FATA Unable to load files: validating [REDACTED]/docker-compose.yml: services.kuard.env_file.0 must be a string 

### Kompose Version

```Text
1.32.0 (765fde254)
```

### Docker-Compose file

```YAML
services:
  kuard:
    image: gcr.io/kuar-demo/kuard-amd64:blue
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override.env
        required: false
    ports:
      - target: 8080
        published: 8080
```
