### ISSUE TITLE
Support adding condition to compose depends_on / warn the user

### ISSUE THREAD

**Issue by aitrics-ray** [kubernetes/kompose#1871]
### What would you like to be added?

I'm trying to convert docker compose via kompose.

```
version: "3.8"

networks:
  shared_network:
    driver: bridge

services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    restart: unless-stopped
    image: 997245385850.dkr.ecr.ap-northeast-2.amazonaws.com/prod/mysql:8.0.36-debian-18a00bd
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ${VOLUME_DIR}/volumes/mysql/:/var/lib/mysql/
      - ${VOLUME_DIR}/logs/mysql/:/var/log/mysql/
    healthcheck:
      test: [ "CMD", "./healthcheck.sh" ]
      interval: 3s
      timeout: 3s
      retries: 100
    networks:
      - shared_network

  backend-migration:
    container_name: backend-migration
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    image: 997245385850.dkr.ecr.ap-northeast-2.amazonaws.com/prod/vc-backend:${VC_IMAGE_TAG}
    entrypoint: [ "sh", "-c", "make migrate" ]
    env_file:
      - ../common_env/vc-backend.env
      - envs/db-encrypt.env
    networks:
      - shared_network
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    container_name: backend
    platform: linux/amd64
    restart: unless-stopped
    image: 997245385850.dkr.ecr.ap-northeast-2.amazonaws.com/prod/vc-backend:${VC_IMAGE_TAG}
    command: uvicorn app.application:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=backend
      - VITALCARE_ENVIRONMENT=development
    env_file:
      - ../common_env/vc-backend.env
      - envs/vc-backend.env
      - envs/db-encrypt.env
      - envs/otel.env
    hostname: api.vitalcare.io
    volumes:
      - ${VOLUME_DIR}/logs/backend/:/data/vc-backend/logs/
      - ${VOLUME_DIR}/admin/:${VC_BACKEND_MOUNT_PATH}
    networks:
      - shared_network
    depends_on:
      backend-migration:
        condition: service_completed_successfully
```

When I run `kompose convert`, I get an error like this.
`FATA services.backend-migration.depends_on must be a list`
My guess is that it's because it's a condition, not a list. Is there a workaround?

### Why is this needed?

There are some things that `depend_on` is not a List.
