### ISSUE TITLE
Regression caused by #1826

### ISSUE THREAD

**Issue by ghost** [kubernetes/kompose#1877]
The PR #1826 caused a regression in our Compose file:

```yml
services:
  a:
    image: alpine:3.19
    command: ["cat", "/etc/hello_world.yaml"]
    secrets:
      - source: hello-world
        target: /etc/hello_world.yaml
secrets:
  hello-world:
    file: config/hello_world.yaml
```

Now, I am unable to `cat /etc/hello_world.yaml`, even though the names of the secret files match in the Compose file.

I would implement this solution differently, without touching any `environment`s:

1. If `target` is specified, only ever transform the `source` field.
2. If `target` is not specified, fill it in as `/run/secrets/{source_before_transform}`.

The output of the original Compose by @sosan should be:

```yml
    spec:
      containers:
        - env:
            - name: MARIADB_ROOT_PASSWORD_FILE
              value: /run/secrets/MARIADB_PASSWORD
          image: mariadb:11
          name: database
          volumeMounts:
            - mountPath: /run/secrets
              name: mariadb-password
              subPath: MARIADB_PASSWORD
      restartPolicy: Always
      volumes:
        - name: mariadb-password
          secret:
            items:
              - key: mariadb-password
                path: MARIADB_PASSWORD
            secretName: mariadb-password
```
