### ISSUE TITLE
[BUG] --with-kompose-annotation=false flag removes custom annotations defined in labels as well

### ISSUE THREAD

**Issue by jancespivo** [kubernetes/kompose#1885]
### Expected Behavior

`--with-kompose-annotation=false` should remove only `kompose.*` annotations not all annotations

### Actual Behavior

`--with-kompose-annotation=false` removes also custom annotations defined in `service[].labels`

### Steps To Reproduce

`kompose convert --with-kompose-annotation=false`

### Kompose Version

```Text
1.33.0 (3ce457399)
```

### Docker-Compose file

```YAML
services:
  web:
    image: nginx
    labels:
      mycustom.annotation: true
```
