### ISSUE TITLE
[BUG] underscores in compose service name are not replaced with dashes in kubernetes Service metadata.name

### ISSUE THREAD

**Issue by jancespivo** [kubernetes/kompose#1897]
### Expected Behavior

`kompose convert` should replace underscores with dashes in kubernetes Service metadata.name when compose service name contains underscores

```
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: myservice-api
  name: myservice-api  # THIS IS OK
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: myservice-api
```

### Actual Behavior

It generates:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: myservice-api
  name: myservice_api  # <-- THIS IS NOT VALID name
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: myservice-api
```

`metadata.name` is not valid (it contains underscore instead of dash)

### Kompose Version

```Text
1.34.0
```

**Comment by kundan2707** [comment]
@jancespivo  can you share steps to reproduce?

**Comment by jancespivo** [comment]
@kundan2707 

`docker-compose.yml`

```yaml
services:
  myservice_api:
    image: nginx:1.22
    ports:
      - target: 80
```

run `kompose convert`

`$ cat myservice_api-service.yaml`

```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: myservice-api
  name: myservice_api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: myservice-api 
```

`metadata.name` is `myservice_api` which is incorrect and should be `myservice-api`
