### ISSUE TITLE
[BUG] OpenShift provider should not use DeploymentConfigs (anymore)

### ISSUE THREAD

**Issue by jacksgt** [kubernetes/kompose#1903]
### Expected Behavior

Kompose should use regular Kubernetes `Deployments` also with `--provider=openshift`.

### Actual Behavior

When invoking `kompose convert --provider=openshift`, kompose currently creates `DeploymentConfig` objects for each docker compose service.
However, as of Openshift 4.14 `DeploymentConfigs` are deprecated.
The Openshift web console shows the following warning:

![Screenshot 2024-06-20 at 12-44-45 DeploymentConfigs · OKD](https://github.com/kubernetes/kompose/assets/11589682/7714bca3-87e0-4062-abb4-8088ae5c1672)

The `oc` CLI shows this warning:

```
$ oc get deploymentconfig 
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
```

### Steps To Reproduce

```
kompose convert -f docker-compose.yml --provider=openshift
```

### Kompose Version

```Text
1.32.0 (HEAD)
```

### Docker-Compose file

```YAML
version: '3.2'

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - LOGGER_LEVEL=INFO
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
      - HIDE_REFERER=true
    ports:
     - 5000
    restart: unless-stopped
  playwright-chrome:
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=2
    ports:
      - 3000
volumes:
  changedetection-data:
```

### Anything else?

https://docs.openshift.com/container-platform/4.15/applications/deployments/what-deployments-are.html
