### ISSUE TITLE
[BUG] services.web.env_file.0 must be a string

### ISSUE THREAD

**Issue by maylife** [kubernetes/kompose#1904]
### Expected Behavior

Should output the `frontend-deployment.yaml` and `frontend-service.yaml` files.

### Actual Behavior

The following error appears:

FATA Unable to load files: validating C:\Users\admin\Documents\Projects\test\compose.yaml: services.frontend.env_file.0 must be a string 

### Steps To Reproduce

1. Run kompose convert -f .\compose.yaml

### Kompose Version

```Text
1.31.2 (a92241f79)
```

### Docker-Compose file

```YAML
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compose.yaml ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
networks:
  docker-network:
  
services:
  frontend:
    image: alpine:latest
    networks: 
      - docker-network
    env_file:
      - path: ./.env
        required: true
    ports:
      - "81:3000"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ .env ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DATABASE_CON= 'URL'
PORT= 80
JWT_SECRET= 'String'
GOOGLE_CLIENT_ID='String'
GOOGLE_CLIENT_SECRET='String'
GOOGLE_CALLBACK_URL='URL'
SESSION_SECRET='String'
BACKEND_URL=https://backend
```

### Anything else?

Running `docker compose up` successfully validates the docker compose file.

Current workaround not using the .env file, instead using the environment settings as shown below:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compose.yaml ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
networks:
  docker-network:
  
services:
  frontend:
    image: alpine:latest
    networks: 
      - docker-network
    environment:
      - DATABASE_CON= 'URL'
      - PORT= 80
      - JWT_SECRET= 'String'
      - GOOGLE_CLIENT_ID='String'
      - GOOGLE_CLIENT_SECRET='String'
      - GOOGLE_CALLBACK_URL='URL'
      - SESSION_SECRET='String'
      - BACKEND_URL=https://backend
    ports:
      - "81:3000"
