### ISSUE TITLE
[BUG] Can't escape interpolation 

### ISSUE THREAD

**Issue by slaskis** [kubernetes/kompose#1906]
### Expected Behavior

Expect `$$REDIS_PASSWORD` to be interpolated according to [the compose spec](https://docs.docker.com/compose/compose-file/12-interpolation/) so into `$REDIS_PASSWORD`.

### Actual Behavior

It interpolated it into `$(REDIS)_PASSWORD`.

### Steps To Reproduce

1. Run `kompose convert`
2. Look into the "redis-deployment.yaml" file and see `$$REDIS_PASSWORD` being interpolated as `$(REDIS)_PASSWORD`

### Kompose Version

```Text
1.34.0 (HEAD)
```

### Docker-Compose file

```YAML
services:
  redis:
    image: redis
    command: redis-server --requirepass $$REDIS_PASSWORD
    ports:
      - 6379
```
