### ISSUE TITLE
Failure on PVC creation: Invalid value: "scooldUploads": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters ...

### ISSUE THREAD

**Issue by hurzelpurzel** [kubernetes/kompose#1942]
### Expected Behavior

Kompose should produce a syntactic valid PVC

### Actual Behavior

 templates/scooldUploads-persistentvolumeclaim.yaml: object name does not conform to Kubernetes naming requirements: "scooldUploads": metadata.name: Invalid value: "scooldUploads": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

### Steps To Reproduce

Use the  File below and put it an helm chart and lint it

### Kompose Version

```Text
1.34.0 (cbf2835db)
```

### Docker-Compose file

```YAML
version: '3.4'

services:
   para:
     image: erudikaltd/para:latest_stable
     ports:
       - "8080:8080"
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: volume
         source: paraLib
         target: /para/lib
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     restart: always
     environment:
       - JAVA_OPTS=-Dconfig.file=/para/application.conf -Dloader.path=/para/lib

   scoold:
     depends_on:
       - para
     image: 374874639893.dkr.ecr.eu-west-1.amazonaws.com/scoold-pro:latest_stable
     ports:
       - "8000:8000"
     volumes:
       - type: volume
         source: scooldUploads
         target: /scoold-pro/uploads
       - type: bind
         source: ./scoold-application.conf
         target: /scoold-pro/application.conf
       - type: bind
         source: ./para-application.conf
         target: /scoold-pro/para-application.conf
     restart: always
     environment:
       - JAVA_OPTS=-Dconfig.file=/scoold-pro/application.conf -Dscoold.autoinit.para_config_file=/scoold-pro/para-application.conf -Dscoold.para_endpoint=http://para:8080
       - BOOT_SLEEP=5
volumes:
  paraData:
  paraLib:
  scooldUploads:
```

### Anything else?

volumes should be lower cased
