### ISSUE TITLE
Support for `content` in top-level config

### ISSUE THREAD

**Issue by jvitor83** [kubernetes/kompose#1947]
### What would you like to be added?

Support for `content` in the top-level `config` as it states in https://docs.docker.com/reference/compose-file/configs/ released in [Docker Compose version 2.23.1](https://docs.docker.com/compose/releases/release-notes/#2231)

```yml
services:

  hello:
    image: nginxdemos/hello
    configs:
      - source: conf-name
        target: /etc/dynamic.yaml

configs:
  conf-name:
    content: |
      some-setting: true
```

Currently it gives:
`FATA Unable to retrieve file: Unable to read file: open : The system cannot find the file specified.`

### Why is this needed?

To keep the compatibility synced between docker-compose and kompose.
