### ISSUE TITLE
Add `no-interpolate` to allow the generated files to keep the variable placeholder

### ISSUE THREAD

**Issue by jvitor83** [kubernetes/kompose#1953]
### Context:
Sometimes we want the generated file to keep the environment variable placeholder, so we can take advantage os scenarios where the generated files still act as a template where the environment variables could be interpolated in a later moment.

### Example:
```yaml
version: '3.8'

services:
  foo:
    image: ${DOCKER_REGISTRY-}foo:${IMAGE_TAG:-latest}
    build: .
    environment:
      - VERSION=${IMAGE_TAG:-latest}
    ports:
      - 80:80
```
to generate:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: foo
  name: foo
spec:
  # ... brevity
    spec:
      containers:
        - env:
            - name: VERSION
              value: ${IMAGE_TAG:-latest}
          image: ${DOCKER_REGISTRY-}foo:${IMAGE_TAG:-latest}
          name: foo
          ports:
            - containerPort: 80
              protocol: TCP
  # ... brevity
```

### How:
Just like we have with `docker compose config --no-interpolate`, we can use the same feature idea.

### Known Problems:
Some of the code we have at this moment "dont support/take in consideration" the possibility of having a "env var placeholder" value like:
```yaml
    ports:
      - ${PORT:-80} # not supported as of now
    labels:
      kompose.image-pull-policy: "${IMAGE_PULL_POLICY:-IfNotPresent}" # not supported as of now
```
as ports expects a integer and not string (and it may have some logic related also). But there is more like labels, for example `kompose.image-pull-policy: "${IMAGE_PULL_POLICY:-IfNotPresent}"` also didn't work because it expect to be have specific "pre-defined" values.

I think initial work in this is to support the basics like "image" and "environments" keys. I believe all the others attributes, can be done in a on-demand basis by others issues specific to each need.

### Why is this needed?

Allow the generated files to keep the environment variable placeholders in order to be interpolated in a later moment.
