### ISSUE TITLE
Add possibility to change kompose specific labels in k8s manifests

### ISSUE THREAD

**Issue by ontec-xrail** [kubernetes/kompose#1960]
### What would you like to be added?

To remove the labels there is already an option:
--with-kompose-annotation=false

But there is still a label generated "io.kompose.service" - it would be cool to have another cmd line flag e.g. "--with-kompose-service-name=app" to get rid of the kompose specific stuff

Sample now:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xxxx-core
  name: xxxx-core
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: xxxx-core
```

Sample later:
kompose convert --with-kompose-annotation=false --with-kompose-service-name=app ...

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxxx-core
  name: xxxx-core
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: xxxx-core
```

### Why is this needed?

generating a clean k8s manifest without kompose leftovers ...
