### ISSUE TITLE
[BUG] WARN Failed to check if the directory is empty: open data: no such file or directory

### ISSUE THREAD

**Issue by mcarbonneaux** [kubernetes/kompose#1977]
### Expected Behavior

no warning !
and normaly the massage must be ERR and not WARN!

### Actual Behavior

when start convertion : WARN Failed to check if the directory is empty: open data: no such file or directory
the directory is not empty, it's containt only one sub directory.

### Steps To Reproduce

```yaml
  myservice:
    image: myimage/myimage
    restart: always
    ports:
      - 5333/tcp
    volumes:
      - /data/mydir:/opt/mydir
```

```
WARN Failed to check if the directory is empty: open data: no such file or directory
WARN Skip file in path /data/mydir
```

the /data/mydir is directory, and contain only one subdir... and /data is directory... and the sub directory containe multiple file...

### Kompose Version

```Text
v1.33.0 and higher
it's work fine in v1.32.0
```

### Docker-Compose file

```YAML
myservice:
    image: myimage/myimage
    restart: always
    ports:
      - 5333/tcp
    volumes:
      - /data/mydir:/opt/mydir
```

### Anything else?

i think the problem is in the function `checkIsEmptyDir`.
they try to recurse the filePath... they found in first a directory `data`...
but when call recursively `checkIsEmptyDir` the use relative name `data`, not the absolute name `/data/mydir/data`...
they break on first os.ReadDir... but is normal because they try to check `data` in place of `/data/mydir/data`.

https://github.com/kubernetes/kompose/blob/9532ceef3ad2bc7908db84f8140f6767106b932d/pkg/transformer/kubernetes/k8sutils.go#L1265-L1284
