### ISSUE TITLE
[BUG] must be a mapping

### ISSUE THREAD

**Issue by az-z** [kubernetes/kompose#1986]
### Expected Behavior

hello,
 thank you for the project!

Expected behavior : 
expect to have docker-compose converted into k3s/k8s deployment file

### Actual Behavior

```ATA Unable to load files: validating /home/az/...../playground/docker-compose.yml: services.vault-agent.depends_on.vault must be a mapping
```

### Steps To Reproduce

curl -L https://github.com/kubernetes/kompose/releases/download/v1.35.0/kompose-linux-amd64 -o ~/bin/kompose && chmod +x ~/bin/kompose

cd playground
kompose  -f docker-compose.yml convert

### Kompose Version

```Text
kompose version
1.35.0 (9532ceef3)
```

### Docker-Compose file

```YAML
services:

  vault-agent:
    build:
      context: .
      dockerfile: vault_agent/Dockerfile
    depends_on:
      vault: service_started

  vault:
    image: hashicorp/vault:latest
```

### Anything else?

I chopped down the compose file just to be able to reproduce the conversion error.
