### ISSUE TITLE
[BUG] "No such file or directory" error when recursively checking directories in checkIsEmptyDir function

### ISSUE THREAD

**Issue by yuefanxiao** [kubernetes/kompose#2022]
### Expected Behavior

When recursively checking if directories are empty using the checkIsEmptyDir function, it should correctly traverse subdirectories by using the full path.

### Actual Behavior

The function fails with an error "open data: no such file or directory" (or similar errors) when trying to check subdirectories. This happens because the recursive call only uses the file name without the parent path:
`_, err := checkIsEmptyDir(file.Name())`
Terminal output example:
`WARN File don't exist or failed to check if the directory is empty: stat :/data: no such file or directory`

### Steps To Reproduce

1. Create a docker-compose.yml file with the following content:
```
services:
  ragflow:
    image: infiniflow/ragflow:v0.17.2-slim 
    container_name: ragflow-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ragflow/data0/:/data
```
2. Run `kompose convert -f docker-compose.yml`
3. Observe the error in the terminal:
`WARN File don't exist or failed to check if the directory is empty: stat /path/to/your/directory/ragflow/data0: no such file or directory`
Note: The error occurs even if you create the directory structure beforehand.

### Kompose Version

```Text
v1.36.0
```

### Docker-Compose file

```YAML
services:
  ragflow:
    image: infiniflow/ragflow:v0.17.2-slim 
    container_name: ragflow-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ragflow/data0/:/data
```

### Anything else?

I would be happy to submit a PR with this fix if needed.
