### ISSUE TITLE
volumeMounts not shared within the initContainers

### ISSUE THREAD

**Issue by ysfmkr** [kubernetes/kompose#2024]
### What would you like to be added?

* Kompose Version: 1.36.0 (HEAD)
* Docker Compose Version: v2.32.4

I have case where I need to convert Docker Compose file into Kubernetes YAML where it have mounted volume. For example, ephemeral Postgres for once-only deployment.

The `docker-compose.yml` looks like this (my idea is to create table schema or maybe some of seed data before container run). But since the generated Kubernetes Spec is not sharing the `volumeMounts` in the `initContainers`, then this script doesn't work.

```yaml
services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: postgres_main
    labels:
      kompose.init.containers.name: "init-myservice"
      kompose.init.containers.image: "busybox:1.28"
      kompose.init.containers.command: '["sh", "-c", "mkdir -p /docker-entrypoint-initdb.d && echo "Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgU0VSSUFMIFBSSU1BUlkgS0VZLAogICAgdXNlcm5hbWUgVkFSQ0hBUiBOT1QgTlVMTCBVTklRVUUsCiAgICBjcmVhdGVkX2F0IFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORSBOT1QgTlVMTCBERUZBVUxUIE5PVygpLAogICAgdXBkYXRlZF9hdCBUSU1FU1RBTVAgV0lUSCBUSU1FIFpPTkUgTk9UIE5VTEwgREVGQVVMVCBOT1coKQopOwo=" | base64 -d  > /docker-entrypoint-initdb.d/docker-postgres-init.sql"]'
      kompose.volume.type: emptyDir
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data/pgdata  # <--- added this line
    ports:
      - "5434:5432"
    volumes:
      - pg-init:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-init: {}
  pg-data: {}
```

The generated `Service` and `Deployment` is look like this:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-showcase-a0f6ab5.yml -o tmpscripts/showcase-kubernetes-spec/
    kompose.image-pull-secret: acr-credential-7b9e06dc9282c7db496ea8cf46426d31
    kompose.init.containers.command: '["sh", "-c", "mkdir -p /docker-entrypoint-initdb.d && echo "Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgU0VSSUFMIFBSSU1BUlkgS0VZLAogICAgdXNlcm5hbWUgVkFSQ0hBUiBOT1QgTlVMTCBVTklRVUUsCiAgICBjcmVhdGVkX2F0IFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORSBOT1QgTlVMTCBERUZBVUxUIE5PVygpLAogICAgdXBkYXRlZF9hdCBUSU1FU1RBTVAgV0lUSCBUSU1FIFpPTkUgTk9UIE5VTEwgREVGQVVMVCBOT1coKQopOwo=" | base64 -d  > /docker-entrypoint-initdb.d/docker-postgres-init.sql"]'
    kompose.init.containers.image: busybox:1.28
    kompose.init.containers.name: init-myservice
    kompose.version: 1.36.0 (HEAD)
    kompose.volume.type: emptyDir
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5432
  selector:
    io.kompose.service: postgres


---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-showcase-a0f6ab5.yml -o tmpscripts/showcase-kubernetes-spec/
    kompose.image-pull-secret: acr-credential-7b9e06dc9282c7db496ea8cf46426d31
    kompose.init.containers.command: '["sh", "-c", "mkdir -p /docker-entrypoint-initdb.d && echo "Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgU0VSSUFMIFBSSU1BUlkgS0VZLAogICAgdXNlcm5hbWUgVkFSQ0hBUiBOT1QgTlVMTCBVTklRVUUsCiAgICBjcmVhdGVkX2F0IFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORSBOT1QgTlVMTCBERUZBVUxUIE5PVygpLAogICAgdXBkYXRlZF9hdCBUSU1FU1RBTVAgV0lUSCBUSU1FIFpPTkUgTk9UIE5VTEwgREVGQVVMVCBOT1coKQopOwo=" | base64 -d  > /docker-entrypoint-initdb.d/docker-postgres-init.sql"]'
    kompose.init.containers.image: busybox:1.28
    kompose.init.containers.name: init-myservice
    kompose.version: 1.36.0 (HEAD)
    kompose.volume.type: emptyDir
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-showcase-a0f6ab5.yml -o tmpscripts/showcase-kubernetes-spec/
        kompose.image-pull-secret: acr-credential-7b9e06dc9282c7db496ea8cf46426d31
        kompose.init.containers.command: '["sh", "-c", "mkdir -p /docker-entrypoint-initdb.d && echo "Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgU0VSSUFMIFBSSU1BUlkgS0VZLAogICAgdXNlcm5hbWUgVkFSQ0hBUiBOT1QgTlVMTCBVTklRVUUsCiAgICBjcmVhdGVkX2F0IFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORSBOT1QgTlVMTCBERUZBVUxUIE5PVygpLAogICAgdXBkYXRlZF9hdCBUSU1FU1RBTVAgV0lUSCBUSU1FIFpPTkUgTk9UIE5VTEwgREVGQVVMVCBOT1coKQopOwo=" | base64 -d  > /docker-entrypoint-initdb.d/docker-postgres-init.sql"]'
        kompose.init.containers.image: busybox:1.28
        kompose.init.containers.name: init-myservice
        kompose.version: 1.36.0 (HEAD)
        kompose.volume.type: emptyDir
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_USER
              value: myuser
          image: docker.io/library/postgres:15
          name: postgres-main
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: pg-init
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      imagePullSecrets:
        - name: acr-credential-7b9e06dc9282c7db496ea8cf46426d31
      initContainers:
        - command:
            - sh
            - -c
            - mkdir -p /docker-entrypoint-initdb.d && echo "Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgU0VSSUFMIFBSSU1BUlkgS0VZLAogICAgdXNlcm5hbWUgVkFSQ0hBUiBOT1QgTlVMTCBVTklRVUUsCiAgICBjcmVhdGVkX2F0IFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORSBOT1QgTlVMTCBERUZBVUxUIE5PVygpLAogICAgdXBkYXRlZF9hdCBUSU1FU1RBTVAgV0lUSCBUSU1FIFpPTkUgTk9UIE5VTEwgREVGQVVMVCBOT1coKQopOwo=" | base64 -d  > /docker-entrypoint-initdb.d/docker-postgres-init.sql
          image: busybox:1.28
          name: init-myservice
      restartPolicy: Always
      volumes:
        - name: pg-init
        - name: pg-data
```

My expected behavior is in every `initContainers` should add `volumeMounts`.

```yaml
 initContainers:
  - command:
      - sh
      - -c
      - mkdir -p /docker-entrypoint-initdb.d && echo "Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgU0VSSUFMIFBSSU1BUlkgS0VZLAogICAgdXNlcm5hbWUgVkFSQ0hBUiBOT1QgTlVMTCBVTklRVUUsCiAgICBjcmVhdGVkX2F0IFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORSBOT1QgTlVMTCBERUZBVUxUIE5PVygpLAogICAgdXBkYXRlZF9hdCBUSU1FU1RBTVAgV0lUSCBUSU1FIFpPTkUgTk9UIE5VTEwgREVGQVVMVCBOT1coKQopOwo=" | base64 -d  > /docker-entrypoint-initdb.d/docker-postgres-init.sql
    image: busybox:1.28
    name: init-myservice
    volumeMounts:
      - mountPath: /docker-entrypoint-initdb.d
        name: pg-init
      - mountPath: /var/lib/postgresql/data
        name: pg-data
```

### Why is this needed?

I think the easiest approach is by appending all existing `volumeMounts` to the `initContainers` because it should be accessed in the same Pod.
