### ISSUE TITLE
allow for setting size of persistent volume

### ISSUE THREAD

**Issue by dustymabe** [kubernetes/kompose#235]
Would be nice to be able to set a size of a volume other than having it hardcoded to [100Mi](https://github.com/kubernetes-incubator/kompose/blob/7435f822ed17837a4d6f472f9a0f800abe1adc95/pkg/transformer/kubernetes/kubernetes.go#L155)

Here is an example of how it is done in docker compose now. I don't think we have to do it this way, just showing an example:

```
# From https://github.com/docker/docker/issues/24318#issuecomment-230410196
version: "2"

services:
  myservice:
    # […]

volumes:
  wangdk2:
    driver: driver-plugin
    driver_opts:
      size: 1G
```
