### ISSUE TITLE
Support for: top-level volumes.

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#447]
Using a top-level volume errors out and is unsupported:
```
version: "2"

services:
    redis:
      image: redis:3.0

volumes:
  - /var/lib/mysql
```

```
ERRO Could not parse config for project wikus : yaml: unmarshal errors:
  line 8: cannot unmarshal !!seq into map[string]interface {} 
FATA Failed to load compose file: yaml: unmarshal errors:
  line 8: cannot unmarshal !!seq into map[string]interface {} 
```
