### ISSUE TITLE
Save the cmd used to create config

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#639]
When we generate config it is really hard to know what command was used to generate that config. And has caused issues in past. As much as important it is to have the docker-compose file to generate the artifacts the command line flags used to generate config are also important, so we should have some way to know what flags were used to generate specific config.

So I propose saving the command given to convert along with flags in annotations of generated configs

like if I use:

```
kompose convert --emptyvols
```

This should show up in the converted annotations like 

```yaml
...
annotations:
  "kompose.cmd": "kompose convert --emptyvols"
  "kompose.version": "0.6.0 (45a0daw)"
...
```

This will help us mitigate issues like https://github.com/kubernetes-incubator/kompose/issues/632

**Comment by kadel** [comment]
This is a good idea.
But maybe instead of full command, it might be better to add something that can be easily parsed.
Or add another extra annotation that will be easy to parse. 

```
 "kompose.data: "{'version': 0.6.0, 'command': 'convert', emptyvols: 'true'} "
```

**Comment by surajssd** [comment]
@kadel yeah even that SGTM!

**Comment by cdrage** [comment]
This sounds great! Would really help in term's of troubleshooting conversions.

**Comment by surajnarwade** [comment]
I am taking this up.

**Comment by surajnarwade** [comment]
Since this will be major change in all unit test case and functional test files, 
I have something output as of now,

```
metadata:
    annotations:
      kompose.cmd: kompose convert --stdout
      kompose.version: |
        1.0.0 (HEAD)
```

Any suggestions before sending PR? @surajssd  @kadel @cdrage

**Comment by surajnarwade** [comment]
This will be the pain for functional tests, as it may be
`kompose convert -f /home/snarwade.....`  for me,

```
metadata:
    annotations:
      kompose.cmd: kompose convert -f /home/snarwade --stdout
      kompose.version: |
        1.0.0 (HEAD)
```

but for travis, `kompose convert -f /home/travis...`
it will be,

```metadata:
    annotations:
      kompose.cmd: kompose convert --stdout
      kompose.version: |
        1.0.0 (HEAD)
metadata:
    annotations:
      kompose.cmd: kompose convert -f /home/travis.... --stdout
      kompose.version: |
        1.0.0 (HEAD)
```
