### ISSUE TITLE
kompose build fails: unable to create tarball

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#656]
kompose build fails: unable to create tarball

my kompose version
```
$ kompose version
0.7.0 (ee79612)
```

when doing local builds on repo https://github.com/pranavgore09/classico/tree/nodejs-service

```bash
✔ ~/git/classico [:9f03f9e|✚ 1] 
12:08 $ git branch 
* (HEAD detached at origin/nodejs-service)
  master
```

I have made changes to the docker-compose file to have my docker hub repo name, docker-compose file looks like this:

```yaml
✔ ~/git/classico [:9f03f9e|✚ 1] 
12:03 $ cat docker-compose.yaml 
version: '2'
services:
  backend:
    image: docker.io/surajd/backend
    build:
      context: ./backend
  gateway:
    image: docker.io/surajd/pranav/gateway
    build:
      context: ./gateway
    ports:
      - "1111:1111"
  daily:
    image: docker.io/surajd/daily-backend
    build:
      context: ./daily-backend
```

running the kompose build command

```bash
✔ ~/git/classico [:9f03f9e|✚ 1] 
12:04 $ kompose up --provider openshift 
INFO Building image 'docker.io/surajd/backend' from directory 'backend' 
INFO Image 'docker.io/surajd/backend' from directory 'backend' built successfully 
INFO Pushing image 'surajd/backend:latest' to registry 'docker.io' 
INFO Multiple authentication credentials detected. Will try each configuration. 
INFO Attempting authentication credentials 'https://index.docker.io/v1/ 
INFO Successfully pushed image 'surajd/backend:latest' to registry 'docker.io' 
INFO Building image 'docker.io/surajd/daily-backend' from directory 'daily-backend' 
FATA Unable to build Docker container for service daily: Unable to create a tarball: archive/tar: write too long 
```

Since the build is big, so i cannot know what is happening in background whether it is stuck or going on.

**Comment by kadel** [comment]
It looks like this problem is caused by symlinks in the build directory. They are not handled properly

**Comment by surajssd** [comment]
@kadel just a note this works if we use buildconfigs to do builds

**Comment by kadel** [comment]
yes, That makes sense as buildconfig is not creating tar. 

The problem is with creating tar that gets sent to docker daemon, it doesn't handle symlinks properly

**Comment by kadel** [comment]
one of the possible solutions is described here https://stackoverflow.com/questions/38454850/getting-write-too-long-error-when-trying-to-create-tar-gz-file-from-file-and-d

**Comment by pvsousalima** [comment]
Hi guys I'm having the same issue as well. Here is my docker-compose.yml:

```
version: '2'

services:

    mongo:
        image: mongo:latest
        restart: always
        environment:
         - MONGO_INITDB_ROOT_USERNAME=user
         - MONGO_INITDB_ROOT_PASSWORD=password
        ports:
         - "27017:27017"

    notifier:
        restart: always
        build:
          context: ./Notifier
        image: staterecordsnotifications_notifier
        volumes:
          - ./Notifier:/opt/app
        ports:
          - "3001:3001"
        links:
          - mongo
```

and it returns 
INFO Build key detected. Attempting to build and push image 'staterecordsnotifications_notifier'
INFO Building image 'staterecordsnotifications_notifier' from directory 'Notifier'
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service notifier: Unable to create a tarball: archive/tar: write too long
