### ISSUE TITLE
error with autogenerated cluster name

### ISSUE THREAD

**Issue by nikhilrayaprolu** [kubernetes/kompose#713]
![image](https://user-images.githubusercontent.com/15216503/28242224-b0a035a4-69c3-11e7-840d-1ef6b1bd2501.png)
![image](https://user-images.githubusercontent.com/15216503/28242227-c7700ae8-69c3-11e7-93df-6dc5b34b3aa1.png)

**Comment by surajnarwade** [comment]
@nikhilrayaprolu , can you paste your docker-compose file here ?

**Comment by surajssd** [comment]
@nikhilrayaprolu your env name is wrong, you cannot define env that has `.` dot in it. You can only have capital and small characters, dashes and underscores and numbers.

Also see the regex in the error:

```
a valid C identifier must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')
```

So change the name of env `cluster.name` to something else, similarly for all other envs.

I don't think kompose can do anything with this other than adding checks on our side. This comes from kubernetes.

**Comment by surajnarwade** [comment]
@nikhilrayaprolu , is your problem resolved, can we close this issue ?

**Comment by nikhilrayaprolu** [comment]
@surajnarwade @surajssd 
here is my docker-compose.yml
```

version: '2'
services:
  yacy_mcp:
    build: .
    links:
      - elasticsearch
    ports:
      - 8100:8100

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=yacygrid
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - "9300"
      - "9200"

    
volumes:
  esdata1:
    driver: local

```
