### ISSUE TITLE
Error running kompose on counter v3 example file

### ISSUE THREAD

**Issue by lucj** [kubernetes/kompose#721]
When running ```kompose convert``` on the newly added `docker-compose-counter-v3.yaml` example file, I got the following error.

```
$ kompose -f docker-compose-counter-v3.yaml convert
ERRO Could not parse config for project examples : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `3` into config.RawService
FATA composeObject.Parse() failed, Failed to load compose file: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `3` into config.RawService
```

**Comment by JadCham** [comment]
@lucj which version of kompose are you using? did you build from master?

**Comment by surajnarwade** [comment]
@JadCham , I build it using master, but today, new version will be released so you can download new binary from there  which will have latest changes.

**Comment by lucj** [comment]
@surajnarwade you'r right, I'm using 0.7.0 (c25b7e8)

**Comment by cdrage** [comment]
@lucj 1.0.0 is coming out today, so you'll be able to download the latest binary and have it work against `docker-compose-counter-v3.yaml`.

**Comment by lucj** [comment]
👍 
In the same time I've built from source and have it working on my compose file version 3.

BTW, on a custom docker-compose, it generates only Pod and PersistentVolumeClaim but no Deployment nor Services. Is there a special key so a Deployment is created (default number of replicas ?).

**Comment by cdrage** [comment]
@lucj It *should* be creating deployments and services. Is your docker-compose file open  for us to test it out?

**Comment by lucj** [comment]
No problem, here is an extract of the compose file I'm using:
```
version: '3'
services:
  api:
    image: lucj/api:develop
    deploy:
      restart_policy:
        condition: on-failure

  authn:
    image: 'lucj/authn:develop'
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: 'mongo:3.4'
    volumes:
      - mongo-data:/data/db
    deploy:
      restart_policy:
        condition: on-failure

  kv:
    image: 'redis:3.0.7-alpine'
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure

  mq:
    image: 'rabbitmq:3.6'
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    deploy:
      restart_policy:
        condition: on-failure

  proxy:
    image: 'lucj/proxy:develop'
    ports:
      - '8000:8000'
      - '8002:8002'
    deploy:
      restart_policy:
        condition: on-failure

  web:
    image: 'lucj/web:develop'
    deploy:
      restart_policy:
        condition: on-failure

  wss:
    image: 'lucj/wss:develop'
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongo-data:
  redis-data:
  rabbit-data:
```
