### ISSUE TITLE
tmpfs with mode fails

### ISSUE THREAD

**Issue by ThHareau** [kubernetes/kompose#807]
Hello, 

Trying to use kompose on [microservices-demo](https://github.com/microservices-demo/microservices-demo), I had to modify the generated files, because a mode is provided for the tmpfs. 
Here is a shortened version of it:

Using this compose file. 

```yml
version: "2"

services:

  redis-master:
    image: gcr.io/google_containers/redis:e2e 
    ports:
      - "6379"
    tmpfs:
      - /tmp:rw,noexec,nosuid
```

This file can be used correctly with docker compose. However, when running `kompose up`, the pod fails to be created: 
```
redis-master-1539052294-z8txm   0/1       rpc error: code = 2 desc = Error response from daemon: {"message":"invalid bind mount spec \"/var/lib/kubelet/pods/c902b3c2-92d6-11e7-8f5f-0200ac100026/volumes/kubernetes.io~empty-dir/redis-master-tmpfs0:/tmp:rw,noexec,nosuid\": invalid mode: rw,noexec,nosuid"}   0         47s

```

```bash 
kompose version
1.1.0 (36652f6)
```
