### ISSUE TITLE
Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by ylogx** [kubernetes/kompose#809]
When I run `kompose up`, I get the following error:
```
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service business-api: Unable to build image. For more output, use -v or --verbose when converting.: API error (500): {"message":"Cannot locate specified Dockerfile: Dockerfile"}
```

My folder structure is: 
```
repo 
  package
    business-api
        Dockerfile
```

My docker-compose.yaml is:
```yaml
version: '2'

services:
  business-api:
    restart: always
    build: ./package/business_api
    image: index.docker.io/company/business-api
    volumes:
      - ./:/usr/src/app:ro
      - ./data:/root/data:ro
    depends_on:
      - some-other-service
```
