### ISSUE TITLE
Do not generate empty services

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/kompose#823]
If ports are not set `kompose` generates empty services. Example:
```
  cs-bitcoin-process:
    image: cybernode/cs-bitcoin-processor:release-0.5.3
    environment:
      CASSANDRA_CONNECTION: cs-elassandra
      KAFKA_CONNECTION: cs-kafka:9092
```
This generates:

    NAME                      CLUSTER-IP      EXTERNAL-IP      PORT(S)                       AGE
    svc/cs-bitcoin-process    None            <none>           55555/TCP                     8h
