### ISSUE TITLE
Add support for "scratch space" volumes

### ISSUE THREAD

**Issue by dkarlovi** [kubernetes/kompose#850]
When running a worker-type container, you'd want it to have some temporary workspace where it can leave temp files, etc, so called "scratch space".

With `compose` and local environments, this would simply be another volume:

```yaml
# docker-compose.yaml
version: 2
services:
  worker:
    volumes:
      - tmp:/tmp
volumes:
  tmp: ~
```

But this would become a full blown PVC on production which is not something you want. Better alternative would be to label the volume (say, `kompose.volume.scratch = true` or something) and transform to an [`emptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume:

```yaml
# dc.yaml
apiVersion: v1
kind: DeploymentConfig
spec:
    template:
        spec:
            containers:
                -
                    volumeMounts:
                      - mountPath: /tmp
                        name: tmp-scratch
            volumes:
              - emptyDir: {}
                name: tmp-scratch
```
