### ISSUE TITLE
insufficient cpu

### ISSUE THREAD

**Issue by u007** [kubernetes/kompose#856]
kompose 1.3.0 ()
Google Cloud SDK 176.0.0
alpha 2017.09.15
bq 2.0.27
core 2017.10.13
gsutil 4.27

hi,

i have this docker-compose file which works fine on docker with gloud gce.
but when deployed using kompose,
i keep getting "insufficient cpu" on either or both redis and nginx pods

even resizing cluster count to 2, it keep giving the same error.
does it take into consideration of resources?
```
version: "3"
services:

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.0001'
          memory: 50M
    restart: "on-failure"

  pdf2htmlex:
    image: 'ukwa/pdf2htmlex:latest'
    ports:
      - '5000:5000'
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 50M
  arxiv:
    image: 'nurtureai/arxivscraper'
    command: 'server'
    ports:
      - '5005:5005'
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 50M
  nginx:
    environment:
      - "ENVNAME=staging"
      - "APPHost=staging_web"
    image: 'nurtureai/nginx-ssl'
    networks:
      - backend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /root/web:/home/app/web
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 50M

networks:
  frontend:
  backend:

volumes:
  db-data:
  web:
  data:
```

**Comment by surajnarwade** [comment]
`kompose` will simply map your cpu in `docker-compose` to k8s, it will not consider amount of resources

**Comment by u007** [comment]
what is k8s?
so means kompose does not follow cpu and memory limit set in docker compose yml?

**Comment by surajnarwade** [comment]
@u007 , k8s --> kubernetes, kompose does follow docker compose yml only,

if you check generated deployment for your `redis` service:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: "104857600"
          requests:
            memory: "52428800"
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
```

`cpu` and `memory` are exactly mapped
