### ISSUE TITLE
Docker compose links section can't support

### ISSUE THREAD

**Issue by xianlubird** [kubernetes/kompose#859]
About compose  introduce links https://docs.docker.com/compose/compose-file/compose-file-v2/#links .
  I have a compose like this:
```
web:
  image: registry.aliyuncs.com/acs-sample/wordpress:4.5
  ports:
    - '80'
  environment:
    WORDPRESS_AUTH_KEY: changeme
    WORDPRESS_SECURE_AUTH_KEY: changeme
    WORDPRESS_LOGGED_IN_KEY: changeme
    WORDPRESS_NONCE_KEY: changeme
    WORDPRESS_AUTH_SALT: changeme
    WORDPRESS_SECURE_AUTH_SALT: changeme
    WORDPRESS_LOGGED_IN_SALT: changeme
    WORDPRESS_NONCE_SALT: changeme
    WORDPRESS_NONCE_AA: changeme
  restart: always
  links:
    - 'db:mysql'
db:
  image: registry.aliyuncs.com/acs-sample/mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
  restart: always
  labels:
    aliyun.logs: /var/log/mysql
```
  kompose will convert db service to db deployment, but the wordpress deplotment will connect db by `mysql` hostname.   So wordpress pods will call that and it can't connect the db database.  Because the `links` can't convert to k8s yaml.

  I have two kinds suggestions:
1.  kompose convert db service to mysql service, just rename deployment name for links, and the new service name is mysql, the wordpress can connect mysql by service name corrently.
2. print warning or error message if compose has links section which alias name is different from service name.

   Can anyone give me some suggestion, and I will create a PR to fix this, Thanks.
