### ISSUE TITLE
volumes long-syntax doesn't work

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/kompose#865]
[Conversion matrix](http://kompose.io/conversion/) specifies that `volumes: long-syntax` works, but it doesn't, because it requires at least `version: '3.2`` in the header to be loaded. For example, this fails to validate with `docker-compose`:

```
version: '3'
services:
  cs-btcd:
    image: cybernode/bitcoin-btcd:temp
    volumes:
      - type: volume
        source: /cyberdata
```
```
✗ docker-compose config 
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.cs-btcd.volumes contains an invalid type, it should be a string
```
The same error is reported by `kompose`:
```
✗ kompose convert
FATA services.cs-btcd.volumes.0 must be a string  
```

Changing version to `3.2` makes `docker-compose config` pass, but `kompose` still fails there:
```
✗ kompose convert       
FATA Version 3.2 of Docker Compose is not supported. Please use version 1, 2 or 3 
```
