### ISSUE TITLE
Error transforming Kubernetes objects

### ISSUE THREAD

**Issue by Arnold1** [kubernetes/kompose#876]
Hi,

i run into some issues with kompose when i run the following command. do you know what is wrong and how to resolve it?
```
kompose convert -f docker-compose.yml
WARN Unsupported links key - ignoring             
WARN Volume mount on the host "./alertmanager/alertmanager.yml" isn't supported - ignoring path on the host 
FATA Error transforming Kubernetes objects: k.UpdateController failed: updateTemplate failed: Unknown restart policy unless-stopped for servicealertmanager
```

docker-compose.yml:
```
version: "2"

services:

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.yml:/etc/prometheus/alert.yml
    links:
      - "alertmanager:alertmanager"

  alertmanager:
    image: prom/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
      - '-log.level=debug'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    links:
      - prometheus-server:prometheus

  go-mux-example:
    image: mux:v1
    ports:
      - 8080:8080
```
