### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pkelleratwork** [kubernetes/kompose#892]
version 1.6.0 (e4adfef)
macOS 10.13.2

kompose convert =

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x221af2b]

goroutine 1 [running]:
github.com/kubernetes/kompose/pkg/loader/compose.dockerComposeToKomposeMapping(0xc4205dc6c0, 0x20, 0xc42045d820, 0x1, 0x1, 0xc4200d35f0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:323 +0x45b
github.com/kubernetes/kompose/pkg/loader/compose.parseV3(0xc4203686f0, 0x1, 0x1, 0x1, 0x1, 0x0, 0x30, 0x27e2280)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:113 +0x22b
github.com/kubernetes/kompose/pkg/loader/compose.(*Compose).LoadFile(0x370a980, 0xc4203686f0, 0x1, 0x1, 0xc4200d3080, 0x0, 0x0, 0x9, 0x7)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/compose.go:186 +0x4d2
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x28a1b28, 0x4, 0x0, 0x28b5b4d, 0x15, ...)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/app/app.go:227 +0x145
github.com/kubernetes/kompose/cmd.glob..func3(0x36d8660, 0x370a980, 0x0, 0x0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/cmd/convert.go:95 +0x4d
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x36d8660, 0x370a980, 0x0, 0x0, 0x36d8660, 0x370a980)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:704 +0x2c6
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x36d8aa0, 0x36d8ee0, 0x2499880, 0x36d8be0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:785 +0x30e
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x36d8aa0, 0x0, 0xc420315f48)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:738 +0x2b
github.com/kubernetes/kompose/cmd.Execute()
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/cmd/root.go:92 +0x31
main.main()
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/main.go:22 +0x20

**Comment by cdrage** [comment]
Okay, that is *so* odd that you're getting my folder... 

```
/home/wikus/dropbox/dev/go/src/github.com
```
Can you post the full command you're using?

**Comment by pkelleratwork** [comment]
ran from the directory containing the docker-compose.yml file i tried converting....

"my"-MacBook-Pro:azure$ kompose convert
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2220eeb]

goroutine 1 [running]:
github.com/kubernetes/kompose/pkg/loader/compose.dockerComposeToKomposeMapping(0xc4200aa780, 0x20, 0xc420428220, 0x1, 0x1, 0xc420143890)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:323 +0x45b
github.com/kubernetes/kompose/pkg/loader/compose.parseV3(0xc42058faf0, 0x1, 0x1, 0x1, 0x1, 0x0, 0x30, 0x27e9f00)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:113 +0x22b
github.com/kubernetes/kompose/pkg/loader/compose.(*Compose).LoadFile(0x3723c40, 0xc42058faf0, 0x1, 0x1, 0xc420143320, 0x0, 0x0, 0x10, 0xf)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/pkg/loader/compose/compose.go:186 +0x4d2
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x28a9a38, 0x4, 0x0, 0x28bda27, 0x15, ...)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/pkg/app/app.go:227 +0x145
github.com/kubernetes/kompose/cmd.glob..func3(0x36f1960, 0x3723c40, 0x0, 0x0)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/cmd/convert.go:95 +0x4d
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x36f1960, 0x3723c40, 0x0, 0x0, 0x36f1960, 0x3723c40)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:704 +0x2c6
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x36f1da0, 0x36f21e0, 0x249fa70, 0x36f1ee0)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:785 +0x30e
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x36f1da0, 0x0, 0xc420227f48)
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:738 +0x2b
github.com/kubernetes/kompose/cmd.Execute()
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/src/github.com/kubernetes/kompose/cmd/root.go:92 +0x31
main.main()
	/private/tmp/kompose-20171212-31628-9y6gll/kompose-1.6.0/main.go:22 +0x20

**Comment by cdrage** [comment]
@pkelleratwork Ah, that's better! 

Are you able to post the docker-compose.yaml file that you are using?

**Comment by pkelleratwork** [comment]
sorry - cant post it here....

**Comment by pkelleratwork** [comment]
its pretty standard, nothing wild. front end, back end, proxy in it.

**Comment by cdrage** [comment]
One thing to check if if you've got any blank environment variables within it. That may be one of the reasons. For example, if you have:

```yaml
env:
  - MYSECRETPASS
```

and `echo $MYSECRETPASS` is blank it may be erroring.

**Comment by pkelleratwork** [comment]
confirmed no blank env variables. there are foo=${bar} using a .env file to populate, but nothing blank

echo $MYSECRETPASS is also blank

**Comment by cdrage** [comment]
Without the `docker-compose.yaml` file I wouldn't be able to diagnose it :( Are you able to create I guess a "fake" docker-compose.yaml file with no revealing information so I can replicate it my end?

**Comment by pkelleratwork** [comment]
here you go... verified I get the same error with this "fake" on...

version: "3"
networks:
  network_here:
    external: true
services:
  proxy:
    image: ${REPO}/proxy:${IMAGE}
    restart: always
    ports:
      - 123
      - 456
    links:
      - api
      - web
    networks:
      - network_here
      - default

  api:
    image: ${REPO}/api:${IMAGE}
    restart: always
    ports:
      - 789
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    environment:
      - FOO_CONFIG
      - NODE_ENV=${API}
      - hostname=${HOST}
      - HOST_NAME=${HOST}
      - db_host=db
      - DB_HOST=db
      - db_name
      - auth_strategy
      - redis_host

  web:
    image: ${REPO}/web:${IMAGE}
    restart: always
    ports:
      - 012
    links:
      - redis
      - api
    depends_on:
      - api
      - redis
    environment:
      - NODE_ENV=${ENV}
      - REDIS_HOST
      - AUTH_HOST
      - API_HOST

  db:
    image: dbimage
    restart: always
    ports:
      - 345
    volumes:
      - ./data/db:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - 678
    volumes:
      - ./data/redis:/data

**Comment by pkelleratwork** [comment]
[fake docker compose.txt](https://github.com/kubernetes/kompose/files/1557061/fake.docker.compose.txt)

**Comment by Code0x58** [comment]
I found the same issue, here is a minimal working `docker-compose.yml` which you can break by removing either of `limits`/`reservations`:
```yml
version: '3'
services:
  something-amazing:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
```

**Comment by cdrage** [comment]
Hey @Code0x58 I was unable to replicate the issue with either your above docker-compose.yaml file or the modified one with limits / reservations removed.

```
version: '3'                                                                                                                                                                                                                                                                      
services:                                                                                                                                                                                                                                                                         
  segfault-central:                                                                                                                                                                                                                                                               
    image: alpine                                                                                                                                                                                                                                                                               
```

**Comment by cdrage** [comment]
Hey @pkelleratwork so it looks like it's an issue with the `v3` implentation.

Changing to `version: 2` in your docker-compose.yaml file will fix it. I have a feeling it's about the environment variable implementation.

**Comment by pkelleratwork** [comment]
thanks @cdrage - I'll give it a shot!

**Comment by cdrage** [comment]
I found out *where* it's happening, https://github.com/kubernetes/kompose/blob/master/pkg/loader/compose/v3.go#L322 

Now it's time to debug and see how to fix it.

Looks like it happens if there is a blank variable somewhere within the implementation.

**Comment by pkelleratwork** [comment]
@cdrage - changed version to "2", it worked :) 

<my>-MacBook-Pro:kompose $ kompose convert
WARN The REPO variable is not set. Substituting a blank string.
WARN The IMAGE variable is not set. Substituting a blank string.
WARN The REPO variable is not set. Substituting a blank string.
WARN The IMAGE variable is not set. Substituting a blank string.
WARN The API variable is not set. Substituting a blank string.
WARN The HOST variable is not set. Substituting a blank string.
WARN The HOST variable is not set. Substituting a blank string.
WARN The REPO variable is not set. Substituting a blank string.
WARN The IMAGE variable is not set. Substituting a blank string.
WARN The ENV variable is not set. Substituting a blank string.
WARN Unsupported root level networks key - ignoring
WARN Unsupported networks key - ignoring
WARN Unsupported depends_on key - ignoring
WARN Volume mount on the host "./data/db" isn't supported - ignoring path on the host
WARN Volume mount on the host "./data/redis" isn't supported - ignoring path on the host
INFO Kubernetes file "api-service.yaml" created
INFO Kubernetes file "db-service.yaml" created
INFO Kubernetes file "proxy-service.yaml" created
INFO Kubernetes file "redis-service.yaml" created
INFO Kubernetes file "web-service.yaml" created
INFO Kubernetes file "api-deployment.yaml" created
INFO Kubernetes file "db-deployment.yaml" created
INFO Kubernetes file "db-claim0-persistentvolumeclaim.yaml" created
INFO Kubernetes file "proxy-deployment.yaml" created
INFO Kubernetes file "redis-deployment.yaml" created
INFO Kubernetes file "redis-claim0-persistentvolumeclaim.yaml" created
INFO Kubernetes file "web-deployment.yaml" created

**Comment by Code0x58** [comment]
Hey @cdrage, the file you pasted had _both_ of them removed, with one of them removed it blows up for me:
```yml
version: '3'
services:
  segfault-central:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 256M
```

**Comment by gak** [comment]
I just got hit with the same issue (and fix) as @Code0x58 mentioned on https://github.com/kubernetes/kompose/issues/892#issuecomment-351675307.

v1.6.0 (e4adfef), macOs 10.13.1 (17B1003)

With a simple service:
```
version: '3'

services:
  nginx:
    image: nginx
```

These work:
```
    deploy:
      resources: {}
```

```
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
```

These don't work:
```
    deploy:
      resources:
        reservations: {}
```

```
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 50M
```

```
    deploy:
      resources:
        limits: {}
```

An error, but not a SIGSEGV for this:
```
    deploy:
      resources:
        resources: {}
        limits: {}
```
