### ISSUE TITLE
Kubernetes specific support in Compose

### ISSUE THREAD

**Issue by Vad1mo** [kubernetes/kompose#917]
With compose 3.4 it is possible to define **extension-fields** with those it would be possible to map them to a structure that only exists in k8s 

https://docs.docker.com/compose/compose-file/#extension-fields

**Comment by cdrage** [comment]
@Vad1mo Good find, that's actually wicked. Could be better rather than using labels..

**Comment by Vad1mo** [comment]
> Starting with the 3.7 format (for the 3.x series) and 2.4 format (for the 2.x series), extension fields are also allowed at the root of service, volume, network, config and secret definitions.

```yaml
version: '2.1'
x-custom:
  items:
    - a
    - b
  options:
    max-size: '12m'
  name: "custom"
```
they backported it now to 2.x
