### ISSUE TITLE
depends_on with conditions

### ISSUE THREAD

**Issue by matt-shaw** [kubernetes/kompose#939]
Hi,

Does kompose support the following contruct?

```
    depends_on:
      reference-discovery-app:
        condition: service_healthy
      reference-config-app:
        condition: service_healthy
```
