### ISSUE TITLE
Kompose doesn't find dockerfile with context .

### ISSUE THREAD

**Issue by BenderV** [kubernetes/kompose#944]
I think I have find two errors:

1 - kompose us searching for context related to directory from where it is run, not from where docker-compose.yml file is located

> kompose up -f docker/docker-compose-dev.yml -v
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service backend-server: ../server is not a valid path for building image backend-server. Check if this dir exists.: stat ../server: no such file or directory

2 - kompose fail to look for dockerfile (if the context is not in a subdirectory ?)  -- could be related: https://github.com/kubernetes/kompose/issues/809 & https://github.com/kubernetes/kompose/issues/832

Error: `{"message":"Cannot locate specified Dockerfile: Dockerfile"}`

Note that docker-compose work well here.
--- 

Structures
```yaml
docker/ -- docker-compose files
   docker-compose-dev.yml 
server/ -- back-end
web/ -- front-end
````

docker-compose-dev.yml 
```yaml
version: '3'

services:
  backend-server:
    image: backend-server:dev
    build:
      context: ../server
      dockerfile: Dockerfile
    volumes:
      - ../templates:/usr/src/templates
    env_file:
      - ../docker_env.list
    ports:
      - 5000:4000

  front-end:
    image: front-end:dev
    build:
      context: ../web
      dockerfile: Dockerfile
    volumes:
      - ../web/src:/usr/src/web/src
      - ../web/config:/usr/src/web/config
      - ../web/build:/usr/src/web/build
      - ../web/static:/usr/src/web/static
    env_file:
      - ../docker_env.list
    ports:
      - 8080:8080
    depends_on:
      - backend-server
```
