### ISSUE TITLE
Merge multiple docker-compose files

### ISSUE THREAD

**Issue by nathan-K-** [kubernetes/kompose#968]
Hey,

First of all, thanks for this great project,
I've run into a very basic issue, when having two docker-compose files, ie:

docker-compose.yml
```
version: '3'

services:
  server:
    image: test
    container_name: test_server
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
```

docker-compose.prod.yml
```
version: '3'

services:
  server:
    ports:
      - 5000:5000
```

With ```kompose convert -f "docker-compose.yml" -f "docker-compose.prod.yml" ```, there is :
```   
     - name: "3000"
      port: 3000
      targetPort: 3000
[...]
      spec:
        containers:
        - image: test:dev
          name: test_server
          ports:
          - containerPort: 3000
```
But nothing about port 5000. (with kompose 1.10.0 (8bb0907), on ubuntu 16.04)

I've seen the PR #312 , but they didn't speak about merging multiple docker-compose files.
Is it planned for a future release ?
 
Thanks
