### ISSUE TITLE
FATA services.xxx.ports.0 must be a string or number

### ISSUE THREAD

**Issue by foxundermoon** [kubernetes/kompose#986]
```yml
    ports:
      - target: 5010
        published: 5010
        protocol: tcp
```
